#!/usr/bin/env node
/**
 * 把 index.html 里 ==ENGINE-START== / ==ENGINE-END== 之间的引擎块抽出来，
 * 写成 src/engine.js（末尾追加导出语句，引擎块本身逐字节不动）。
 *
 * 为什么用抽取而不是复制：index.html 是引擎的唯一真源。复制一份就有两份，
 * 迟早各自漂移；抽取 + 逐字节判据（test/verify-engine-copy.mjs）把这件事
 * 变成可证伪的约束。
 */
import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(HERE, '../..');
const SRC_HTML = resolve(REPO_ROOT, 'index.html');
const OUT = resolve(HERE, '../src/engine.js');

const START = '/* ==ENGINE-START== */';
const END = '/* ==ENGINE-END== */';

/** 需要导出的顶层名字 —— 只列实际用到的，不多不少。 */
export const EXPORTS = [
  'TIMBRES', 'TIMBRE_TIERS', 'TIMBRE_TIER_LABELS', 'DEFAULT_TIER',
  'GROOVES', 'METERS', 'DEFAULT_METER',
  'timbreNames', 'timbreLabel', 'timbreTierOf',
  'normalizeScore', 'durationOf', 'beatsOf', 'meterOf', 'clamp',
  'buildBus', 'scheduleRange', 'mkGain', 'renderOffline', 'encodeWavAsync', 'HEADROOM',
  'midiToName', 'pitchToMidi', 'fmtTime',
];

export function extractEngineBlock(html) {
  const a = html.indexOf(START);
  const b = html.indexOf(END);
  if (a < 0 || b <= a) throw new Error('index.html 中找不到 ENGINE 标记');
  return html.slice(a + START.length, b);
}

/** 语法自检 + 确认每个待导出名字真的存在（否则 export 会在运行时报错）。 */
export function buildModule(block) {
  const probe = block + '\nreturn {' + EXPORTS.join(',') + '};';
  let names;
  try {
    names = new Function(probe)();
  } catch (err) {
    throw new Error('引擎块语法自检失败：' + err.message);
  }
  const missing = EXPORTS.filter((n) => names[n] === undefined);
  if (missing.length) throw new Error('引擎块里找不到这些顶层名字：' + missing.join(', '));
  return [
    '// GENERATED by scripts/extract-engine.mjs —— 请勿直接编辑。',
    '// 唯一真源：仓库根的 index.html（==ENGINE-START== / ==ENGINE-END== 之间）。',
    '// 一致性由 test/verify-engine-copy.mjs 守着。',
    block.trimEnd(),
    '',
    'export {',
    EXPORTS.map((n) => '  ' + n + ',').join('\n'),
    '};',
    '',
  ].join('\n');
}

/** 供 TypeScript 用的边车声明：引擎是 JS，类型手写在这里。 */
const DTS = `// GENERATED by scripts/extract-engine.mjs —— 请勿直接编辑。
export declare const TIMBRES: Record<string, { label?: string; use?: string;[k: string]: unknown }>;
export declare const TIMBRE_TIERS: { basic: string[]; enhanced: string[]; pro: string[] };
export declare const TIMBRE_TIER_LABELS: Record<string, string>;
export declare const DEFAULT_TIER: string;
export declare const GROOVES: Record<string, unknown>;
export declare const METERS: Record<string, { beats: number }>;
export declare const DEFAULT_METER: string;
export declare function timbreNames(tier: string): Array<{ name: string; label: string; use?: string }>;
export declare function timbreLabel(name: string): string;
export declare function timbreTierOf(name: string): string | null;
export declare function normalizeScore(
  raw: unknown, forcedMode?: string, tier?: string, forcedMeter?: string, groove?: string,
): { score: any; warn: string[] };
export declare function durationOf(score: any): number;
export declare function beatsOf(score: any): number;
export declare function meterOf(score: any): string;
export declare function clamp(v: number, a: number, b: number): number;
export declare function buildBus(ctx: any, dest: any, o: { volume?: number; analyser?: any }, score: any): any;
export declare function scheduleRange(ctx: any, bus: any, score: any, opts: any): number;
export declare function mkGain(ctx: any): any;
export declare function renderOffline(score: any, opts?: any): Promise<any>;
export declare function encodeWavAsync(buffer: any, onProgress?: (done: number, total: number) => void): Promise<Uint8Array>;
export declare const HEADROOM: number;
export declare function midiToName(midi: number): string;
export declare function pitchToMidi(p: unknown): number | null;
export declare function fmtTime(sec: number): string;
`;

/**
 * 这个插件可以脱离弦外主仓库单独发布：发布出去的仓库里没有 index.html，
 * 但 src/engine.js（生成物）是随包一起带着的，照常能构建。
 * 那种情况下**不覆盖**已发布的 engine.js，并且把这件事大声说出来——
 * 绝不能悄悄跳过，否则「引擎被改坏了」和「没同步」两种情况就分不清了。
 */
export function sourceAvailable() {
  return existsSync(SRC_HTML);
}

export function build() {
  if (!sourceAvailable()) {
    return { skipped: true, reason: `找不到引擎真源 ${SRC_HTML}（本仓库是插件的独立发布版）` };
  }
  const block = extractEngineBlock(readFileSync(SRC_HTML, 'utf8'));
  const out = buildModule(block);
  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, out);
  writeFileSync(OUT.replace(/\.js$/, '.d.ts'), DTS);
  return { skipped: false, bytes: out.length, block: block.trimEnd().length };
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const r = build();
  if (r.skipped) {
    console.log(`[跳过] ${r.reason}`);
    console.log('[跳过] 继续使用仓库里已有的 src/engine.js（它与主仓库的引擎逐字节一致）。');
  } else {
    console.log(`engine.js 已生成：${r.bytes} 字节（引擎块 ${r.block} 字节）`);
  }
}
