// GENERATED by scripts/extract-engine.mjs —— 请勿直接编辑。
export declare const TIMBRES: Record<string, { label?: string; use?: string;[k: string]: unknown }>;
export declare const TIMBRE_TIERS: { basic: string[]; enhanced: string[]; pro: string[] };
export declare const TIMBRE_TIER_LABELS: Record<string, string>;
export declare const DEFAULT_TIER: string;
export declare const GROOVES: Record<string, unknown>;
export declare const METERS: Record<string, { beats: number }>;
export declare const DEFAULT_METER: string;
export declare function timbreNames(tier: string): Array<{ name: string; label: string; use?: string }>;
export declare function timbreLabel(name: string): string;
export declare function timbreTierOf(name: string): string | null;
export declare function normalizeScore(
  raw: unknown, forcedMode?: string, tier?: string, forcedMeter?: string, groove?: string,
): { score: any; warn: string[] };
export declare function durationOf(score: any): number;
export declare function beatsOf(score: any): number;
export declare function meterOf(score: any): string;
export declare function clamp(v: number, a: number, b: number): number;
export declare function buildBus(ctx: any, dest: any, o: { volume?: number; analyser?: any }, score: any): any;
export declare function scheduleRange(ctx: any, bus: any, score: any, opts: any): number;
export declare function mkGain(ctx: any): any;
export declare function renderOffline(score: any, opts?: any): Promise<any>;
export declare function encodeWavAsync(buffer: any, onProgress?: (done: number, total: number) => void): Promise<Uint8Array>;
export declare const HEADROOM: number;
export declare function midiToName(midi: number): string;
export declare function pitchToMidi(p: unknown): number | null;
export declare function fmtTime(sec: number): string;
