// GENERATED by scripts/extract-engine.mjs —— 请勿直接编辑。
// 唯一真源：仓库根的 index.html（==ENGINE-START== / ==ENGINE-END== 之间）。
// 一致性由 test/verify-engine-copy.mjs 守着。

const NOTE_OFFSETS = { c: 0, d: 2, e: 4, f: 5, g: 7, a: 9, b: 11 };
const WAVES = ["sine", "triangle", "sawtooth", "square"];
const PERC_KINDS = ["kick", "snare", "hat", "clap", "tom"];
const FILTER_TYPES = ["lowpass", "highpass", "bandpass", "none"];

/* ── 音色库 ────────────────────────────────────────────────────────────────
 *
 * 原来"音色"就等于 osc.type 的 4 个枚举值，所有音的滤波与包络都写死，
 * 于是不同曲子听着都像一个模子。这里把音色抽成「名字 → 参数包」，
 * 同时按三档把名字集合放开，让模型能表达的音色随档位变丰富。
 *
 * 参数含义（缺省即不启用，保持与旧版逐样本一致）：
 *   type    内置波形，与 harm 互斥
 *   harm    谐波幅度数组，**下标 k 就是第 k 次谐波**（0 号是直流，留空）。
 *           走 setPeriodicWave。注意：osc.type = "custom" 在 setPeriodicWave
 *           之前赋值会抛 InvalidStateError（浏览器实测），所以只能设波、不设 type。
 *   detune  失谐量（音分）。给了就再叠一个同波形的振荡器，做出弦乐群/pad 的厚度。
 *   fm      {ratio, index} 调制器：载波之外多一个振荡器，频率 = freq × ratio，
 *           频偏 = freq × index。钟琴/电钢/金属这类非谐分音只能靠它。
 *   noise   {gain, decay, band} 噪声起振（气声/弓擦）。多一个噪声源 + 带通。
 *   fcut    低通截止 = freq × fcut（旧版恒为 7）
 *   fq      低通 Q（旧版恒为 0.7）
 *   fenv    [起始倍数, 结束倍数, 秒]：截止在 freq×起始 → freq×结束 之间扫。
 *           拨弦的"亮起振→暗余音"、铜管的"blat"全靠它，且**不新增任何节点**。
 *   amp     [起振, 衰减, 保持电平, 释放] 秒。不给就沿用旧的"随 dur 推导"。
 *   trim    响度微调。createPeriodicWave 默认会把波形峰值归一化，
 *           各音色的实测响度本就不齐，这里按测量值拉平，否则"换音色"会变成"换音量"。
 *   label   中文名，用于图例与提示词。
 *   keyTrack 键盘跟踪比例 kt：主低通截止 = 220 × fcut × (f0/220)^kt。**锚在 A3（f0 = 220）**，
 *           所以 kt 取任何值 A3 都逐位不变；缺省 1 = 与旧版逐位等价（100% 跟踪）。
 *           业界档位 0/33/50/67/100%（Yamaha AN-X），真乐器落在 50~70%。
 *   body    [{f,q,gain}]：**固定 Hz** 的琴体/管体共振峰（不随音高移动）—— 真乐器的体共振
 *           是"pitch-independent, fixed maxima in the spectrum"（Vienna）。低 Q 双极点
 *           peaking，增益再乘音区权重（低音大、高音小）；Q 与衰减 t60 ≈ 2.198·Q/f，
 *           表里的 q 是 A2 处的实测值，更低的音按 1/f² 规律拉长（上限 24）。
 *           **只花滤波器、不占音源预算。**
 *   high    {lo,hi,harm,formants}：**高音区逃生舱**，语义与 low 镜像（f0 ≥ hi → 全量、
 *           ≤ lo → 0）。给"高音区反而更亮/更鼻音"的乐器（长笛、铜管的超吹音区）。
 *   cutMax  截止的**绝对 Hz 上限**（安全阀，可选）。约束 cutMax ≥ 220×fcut 且 ≥ 220×fenv[0]。
 *   use     音区提示（一句话）：进提示词，告诉模型这个音色在低/中/高音区各是什么样。
 *
 * 三档只决定「给模型开放的词表大小」：基础 4（内置波形）/ 增强 18 / 专业 32，高档 ⊃ 低档。
 * 成本**不再由档位决定**，而由乐谱里实际用到的音色决定 —— 离线渲染耗时 ≈ 曲长 × 音源数
 * （实测，超线性），而每个具名音色**每音最多多 2 个音源**（`detune`/`fm`/`noise`/`breath`
 * 各 +1，可叠加但总增量 ≤ 2；tools/verify-timbres.mjs [6] 会守住这条）。基础档那 4 个
 * 内置波形仍是每音恰好 1 个音源。音区自适应（keyTrack / body / high / cutMax）**只花滤波器
 * 与数组算术，音源增量为 0** —— 所以「低音厚、中音原样、高音瘦」这一层不花导出时间。
 *
 * 三档的真实导出耗时（`tools/bench-timbre-long.mjs`，8 轨 + 打击乐，每档各跑一次，单位秒。
 * **注意这组数字测的是当时的音色轮转**：增强档跑 organ/pad/pluck/strings、专业档跑
 * bell/lead/choir/flute/piano/metal —— 换一批音色数字就会变，别当档位的固有属性读）：
 *
 *   小节   时长   音源数   基础     增强     专业    专业/基础
 *    16    40s     288    2.3      2.7      3.6     ×1.54
 *    48   120s     864   21.5     22.0     34.4     ×1.60
 *   120   300s    2160  188.3    217.4    411.4     ×2.18
 *
 * 两个从实测读出来的、与直觉相反的事实，别再凭想象写文案：
 *   1. **差距随曲长放大，不收敛**（×1.54 → ×2.18）。原因不是新增节点的绝对量，
 *      而是超线性曲线在长曲上被拉陡：多音源的音色把音源数抬高到 1.28 倍，落在陡段就是 2 倍代价。
 *   2. **"零新增节点"不等于"耗时相同"**：增强档那组的短曲 ×1.17 可以忽略，但 5 分钟档
 *      +29s（×1.16）已可感知 —— 谐波谱/滤波包络的实际计算量并非零。
 *   ⇒ 文案只能说"取决于用到的音色"，不能说"档位决定快慢"；5 分钟曲用满多音源音色会到
 *     ~7 分钟，必须给出用时反馈（导出按钮的"渲染中… Ns"计时器就是为此，见 renderOffline 调用处）。
 */
const TIMBRES = {
  /* ── 基础档：与旧版完全等价，走原代码路径（plain: true） ── */
  sine: { plain: true, label: "正弦" },
  triangle: { plain: true, label: "三角" },
  sawtooth: { plain: true, label: "锯齿" },
  square: { plain: true, label: "方波" },

  /* ── 增强档 14 个具名音色（原专业档那批）：管风琴 … 长笛 ──
     靶子都是真乐器的三件事：起振多快、谐波怎么衰减、余音怎么收。
     音源：8 个是零新增（纯谐波谱 + 滤波/扫频 + 包络）；钟琴/钢琴/金属/主奏/人声/长笛
     各自多用 1~2 个（FM 调制器 / 失谐层 / 噪声源 / 气声层）—— 上限仍 ≤ +2。 */

  /* 管风琴：气阀一开就满声、按住不退；谐波是整数倍泛音列（8′/4′/2′ 音栓混合）。
     原来只留 1/2/4/8 四根，听着像加了混响的正弦。 */
  organ: {
    harm: [0, 1, 0.55, 0.3, 0.4, 0.15, 0.2, 0.1, 0.25], fcut: 10, fq: 0.5,
    amp: [0.012, 0.04, 0.92, 0.1], trim: 1, label: "管风琴",
    /* 音区自适应：音管共振由**管长**决定 = 固定 Hz（600/1200/2000Hz 借用 Backus 管乐共振峰
       表的量级：长号 600~800、小号 1200~1400/2500），低音区加厚；高音区只用 55% 跟键 ——
       管风琴越高音区越该"稳"，不该跟着变亮。 */
    keyTrack: 0.55,
    body: [{ f: 600, q: 3, gain: 3 }, { f: 1200, q: 2.5, gain: 2.5 }, { f: 2000, q: 2, gain: 1.5 }],
    use: "低音区管体共振加厚；中音区原样；高音区截止只按 55% 跟键，越高越稳不刺",
  },
  /* 铜管：起振要有"吹开"的决断感，截止从高急扫到低就是那声 blat；
     谐波必须宽且缓降 —— 降太快就变成簧管了。 */
  brass: {
    harm: [0, 0.85, 0.9, 1, 0.85, 0.7, 0.55, 0.42, 0.3, 0.22, 0.15], fcut: 7, fq: 1,
    fenv: [12, 3.5, 0.22], amp: [0.05, 0.1, 0.72, 0.16], trim: 1, label: "铜管",
    keyTrack: 0.65,
    /* 喇叭的固定共振峰（调研文档实测表：1200/2400/3400Hz，t60 0.014/0.010/0.008s
       → Q = f·t60/2.198 = 7.6/10.9/12.4 取整）。"抬频段而不是抬音高"就是铜管的音区感来源。 */
    body: [{ f: 1200, q: 8, gain: 3 }, { f: 2400, q: 11, gain: 3 }, { f: 3400, q: 12, gain: 2.5 }],
    /* 高音区逃生舱：铜管的超吹音区**反而更亮更"炸"**（小号 1200~1400/2500Hz 的共振峰被高次
       分音扫到）。高音区换一张更平的分音表 + 2500Hz 低 Q 峰。 */
    high: { lo: 220, hi: 523, harm: [0, 0.8, 0.85, 1, 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.32, 0.26, 0.2],
            formants: [{ f: 2500, q: 1.2, gain: 3 }] },
    /* 安全阀：A5 上 fenv 起始 = 220×12×4^0.65 ≈ 6.5kHz，不封顶顶端会刺耳 */
    cutMax: 5000,
    use: "低音区喇叭共振加厚；中音区原样；高音区换更亮的分音表（超吹），5kHz 上限兜底",
  },
  /* 弦乐：弓子起振慢，而且是"越拉越亮"（截止从低往高扫，与拨弦正相反）。
     谐波要奇偶都有、但**比 1/k 降得快** —— 第一版写成平缓下降，实测反而更像内置锯齿
     （谐波维距离从 0.2198 缩到 0.1315）；现在的靶子是"第 3 次之后按 -9dB/倍频程滚降"。 */
  strings: {
    harm: [0, 1, 0.68, 0.4, 0.22, 0.12, 0.07, 0.045, 0.03, 0.02, 0.013], fcut: 7.5, fq: 0.6,
    fenv: [2.5, 7.5, 0.45], amp: [0.38, 0.25, 0.85, 0.55], trim: 1, label: "弦乐",
    keyTrack: 0.6,
    /* 小提琴琴体模态（调研文档实测表，取四个主模态）：275(Q24,w0.90)/550(22,1.00)/
       2350(6,0.75)/2750(6,0.55)。琴体共振固定 Hz → 低音区落在共振峰里的分音多 = 厚。 */
    body: [{ f: 275, q: 24, gain: 5 }, { f: 550, q: 22, gain: 6 },
           { f: 2350, q: 6, gain: 4.5 }, { f: 2750, q: 6, gain: 3.3 }],
    use: "低音区 275/550/2350/2750Hz 琴体共鸣加厚；中音区原样；高音区跟键 60% → 越高越纯越暗",
  },
  /* 拨弦：指甲扫过弦那一瞬极短；余音要有 0.8s 才像"弦"而不是"敲木头"；
     亮起振→暗余音（截止 16× → 2.5×）。 */
  pluck: {
    harm: [0, 1, 0.62, 0.45, 0.34, 0.26, 0.2, 0.15, 0.11, 0.08, 0.06, 0.04, 0.03],
    fcut: 3, fq: 1.1, fenv: [16, 2.5, 0.35],
    amp: [0.004, 0.85, 0, 0.2], trim: 1, label: "拨弦",
    keyTrack: 0.7,
    /* 吉他琴体模态（调研文档实测表）：100/200/400/550Hz，t60 0.12/0.08/0.06/0.05s →
       Q = f·t60/2.198 = 5.5/7.3/10.9/12.5；权重 1.0/0.7/0.5/0.35 → 增益按 5dB 满档折算。 */
    body: [{ f: 100, q: 5.5, gain: 5 }, { f: 200, q: 7.3, gain: 3.5 },
           { f: 400, q: 11, gain: 2.5 }, { f: 550, q: 12.5, gain: 1.8 }],
    /* 安全阀：fenv 起始 16× 在 A5 上是 220×16×4^0.7 ≈ 9.3kHz，不封顶顶端发烫 */
    cutMax: 6000,
    use: "低音区 100~550Hz 琴体共鸣加厚；中音区原样；高音区跟键 70%、6kHz 封顶",
  },
  /* 马林巴（原槽位是"玻璃"）：木质敲击的分音是"基频强 + 第 4 次谐波突出、2/3 次很弱"，
     跟钟琴/金属那类非谐金属声彻底分开；余音约 0.5s。仍零新增音源。 */
  marimba: {
    harm: [0, 1, 0.08, 0.12, 0.45, 0.05, 0.08, 0.04], fcut: 6, fq: 0.8,
    fenv: [8, 4, 0.3], amp: [0.003, 0.55, 0, 0.25], trim: 1, label: "马林巴",
    keyTrack: 0.6,
    /* 共鸣管本该**随音跟踪**（调研文档：{f0, t60 0.08, w1.2} + {4·f0, 0.04, 0.3}），但 body
       按机制只能是固定 Hz —— 折中：把 A3 的两个管子频率钉成固定值（220/880Hz，Q 由 t60
       反解 8.0/16），"跟音"那部分交给 keyTrack(0.6)。如实记进 report.md 的未落地项。 */
    body: [{ f: 220, q: 8, gain: 5 }, { f: 880, q: 16, gain: 1.3 }],
    use: "低音区 220/880Hz 共鸣管位置加厚；中音区原样；高音区跟键 60%，低音木条更厚更响",
  },
  /* 铺垫：四个谐波太薄（听着像风琴），补到八个并整体压暗；起振保持"涌上来"的 0.62s。 */
  pad: {
    harm: [0, 1, 0.42, 0.2, 0.11, 0.07, 0.05, 0.03, 0.02], fcut: 5, fq: 0.6,
    amp: [0.62, 0.35, 0.9, 0.85], trim: 1, label: "铺垫",
    keyTrack: 0.5,
    /* 合成音色没有实测模态；只借"箱体"这个概念做两个**低 Q 宽峰**（Q < 1 ≈ 两个八度宽的
       柔和倾斜），作用是把低音区整体垫厚，不做中频染色。 */
    body: [{ f: 300, q: 0.9, gain: 3 }, { f: 900, q: 0.8, gain: 2 }],
    use: "低音区两个低 Q 宽峰垫厚；中音区原样；高音区跟键 50%，越高越暗越柔",
  },
  /* 簧管：簧片的唯一听感特征是**奇次谐波占优**（1/3/5/7 强、偶次很弱）。
     原来是 1/4/6/8 混着，所以不像簧片。 */
  reed: {
    harm: [0, 1, 0.12, 0.62, 0.08, 0.35, 0.05, 0.2, 0.03], fcut: 10, fq: 0.9,
    fenv: [8, 10, 0.12], amp: [0.035, 0.09, 0.82, 0.14], trim: 1, label: "簧管",
    keyTrack: 0.65,
    /* 双簧管共振峰（Backus 表：1400/3000Hz）。Q 取 4：簧片乐器的共振峰比琴体模态宽。 */
    body: [{ f: 1400, q: 4, gain: 4 }, { f: 3000, q: 4, gain: 3 }],
    /* 低音区（chalumeau）把**偶次分音抬起来 + 尾巴拉到 13 次**：低音区的簧片谱更厚更圆，
       而 13 次谐波在 A2 上正好是 1430Hz —— 落在 1400Hz 簧管共振峰里，这是"厚"的来源。
       前 8 项之外的尾巴只有低音区够得着（高音区谐波早被截止压掉了）。 */
    low: { hi: 220, lo: 145,
           harm: [0, 1, 0.30, 0.66, 0.17, 0.42, 0.11, 0.26, 0.07, 0.055, 0.042, 0.032, 0.025, 0.019] },
    /* 高音区逃生舱：**寄存器孔/超吹**把"奇次占优"的谱换成含偶次的新谱（调研文档：
       音区边界偶分音 ×0.3→1.0、三次分音 ×1.4）—— 这就是单簧管十二度跳的听感。 */
    high: { lo: 220, hi: 523, harm: [0, 1, 0.3, 0.87, 0.2, 0.35, 0.13, 0.2, 0.08] },
    use: "低音区 1400/3000Hz 簧管共振；中音区原样；高音区超吹，偶次分音抬起来（转亮）",
  },
  /* 低音：要能听出"弹"这一下 —— 8ms 起振 + 截止扫频；谐波压在 4 根以内，多了就糊。 */
  bass: {
    harm: [0, 1, 0.35, 0.16, 0.07], fcut: 4, fq: 0.7,
    fenv: [7, 2.5, 0.18], amp: [0.008, 0.5, 0.25, 0.12], trim: 1, label: "低音",
    keyTrack: 0.7,
    /* 贝斯/电贝斯的箱体模态：借用调研文档的吉他实测表 100/200/400/550Hz（同族木箱体）。 */
    body: [{ f: 100, q: 5.5, gain: 5.5 }, { f: 200, q: 7.3, gain: 4.5 },
           { f: 400, q: 11, gain: 3.5 }, { f: 550, q: 12.5, gain: 2.5 }],
    /* 低音区（A2 及以下）的谱要更厚：2~4 次分音抬 3~8dB + 尾巴补到 7 次，
       和 200/400Hz 两个箱体共振叠在一起就是"低音区的贝斯"。 */
    low: { hi: 220, lo: 145, harm: [0, 1, 0.52, 0.30, 0.17, 0.11, 0.07, 0.045] },
    use: "低音区 100~550Hz 箱体共鸣加厚、谱更厚；中音区原样；高音区跟键 70%，仍留着'弹'的轮廓",
  },

  /* ── 专业档新增 14 个（键盘 / 管弦 / 打击 / 世界 / 电子）──
     每音最多多 2 个音源（musicbox 用满：1 个 FM 调制器 + 1 个噪声源；8 个新音色是 0 新增）。 */
  /* 钟琴与金属的**分工**（老板反馈"两个听着一样"，故这对音色按一条规则分开）：
       钟琴 = **有音高、余音长**：调制指数压到 1.1，让基频站得住（实测基频占能量 0.84）；
              余音 2.4s 才叫敲钟；比例 3.0 的边带给出 2/4 次分音（上谐/基频 0.92）。
       金属 = **无音高、余音极短**：调制指数拉到 11（比例 8.2），边带密到听不出音高
              （实测基频只占 0.14）；余音 0.3s + 高 Q 扫描，是"敲铁板"不是"敲钟"。
     两者手段都是 FM，所以每音仍只多 1 个音源 —— 导出耗时不受影响。 */
  bell: {
    harm: [0, 1, 0.35, 0.2], fm: { ratio: 3, index: 1.1 }, fcut: 12, fq: 0.5,
    amp: [0.002, 2.4, 0, 1], trim: 1, label: "钟琴",
    keyTrack: 0.55,
    /* 钟体是**铸造出来就固定**的模态（敲哪个音都是同一组），所以固定 Hz 比跟踪更物理正确；
       数值借用同族金属体共振的量级（铜管喇叭 1200/2400/3400Hz，加了钟体低频模态 500Hz）。 */
    body: [{ f: 500, q: 4, gain: 3.5 }, { f: 1200, q: 5, gain: 3.5 }, { f: 2400, q: 5, gain: 2 }],
    /* 低音区（大钟）的谱更厚：2~4 次分音抬起来、尾巴补到 7 次（A2 上 4 次 = 440Hz 落在
       500Hz 钟体模态里）。 */
    low: { hi: 220, lo: 145, harm: [0, 1, 0.5, 0.34, 0.22, 0.13, 0.08, 0.05] },
    cutMax: 4500,   // 安全阀：fcut 12 → A3 上 2.64kHz（不受影响），A5 不封顶会到 6kHz
    use: "低音区钟体固定模态加厚；中音区原样；高音区跟键 55% + 4.5kHz 上限，越高越短越纯",
  },
  /* 钢琴：锤击瞬态用噪声起振做，**不用 FM** —— 电钢那版用整数比 FM，做出的其实
     是"带点电味的持续音"，而钢琴的关键是击弦瞬态 + 高次泛音快速衰减（亮起振→暗余音，
     靠 fenv）。音源增量仍是 1（噪声源换掉调制器），导出耗时与替换前持平。 */
  piano: {
    harm: [0, 1, 0.62, 0.42, 0.3, 0.2, 0.14, 0.1, 0.07, 0.05, 0.035, 0.025],
    noise: { gain: 0.13, decay: 0.028, band: 3200 },
    fcut: 9, fq: 0.7, fenv: [9, 2.2, 0.55],
    amp: [0.005, 1.8, 0.15, 0.45], trim: 1, label: "钢琴",
    keyTrack: 0.65,
    /* 音板/琴体的低频模态调研文档没给；按"同族木制琴体"借用吉他表 100/200/400/550Hz，
       只给低音区加权。**本轮不碰上一轮拍板"别改"的三件事**（力度→音色、双弦/三弦、
       非谐性）：钢琴仍然是非谐性增量为 0 的谐波谱。 */
    body: [{ f: 100, q: 5.5, gain: 4 }, { f: 200, q: 7.3, gain: 3 },
           { f: 400, q: 11, gain: 2 }, { f: 550, q: 12.5, gain: 1.5 }],
    use: "低音区音板低频模态加厚；中音区原样；高音区跟键 65%，越高越干净短促",
  },
  /* 金属：与钟琴**分工见上**（无音高、极短）。高 Q（fq 3）在截止处造一个共振峰，
     那一小段"当"的金属味就来自它，0.07s 内从 18× 扫到 7× 让共振峰快速落下来。 */
  metal: {
    harm: [0, 1, 0.5, 0.3], fm: { ratio: 8.2, index: 11 }, fcut: 18, fq: 3,
    fenv: [18, 7, 0.07], amp: [0.001, 0.3, 0, 0.16], trim: 1, label: "金属",
    keyTrack: 0.7,
    /* 金属体模态固定（同钟琴）。 */
    body: [{ f: 1200, q: 6, gain: 3 }, { f: 2400, q: 6, gain: 2.5 }, { f: 3400, q: 6, gain: 2 }],
    cutMax: 8000,   // 安全阀：fcut 18 → A3 上 3.96kHz，A5 不封顶会到 10.4kHz（敲铁板变吹口哨）
    use: "低音区金属体模态加厚；中音区原样；高音区跟键 70% + 8kHz 上限，保持'敲'不是'啸'",
  },
  /* 合成主奏（原槽位是"宽弦"）：宽弦 = 弦乐 + 失谐，跟增强档的 strings 撞车；
     换成 supersaw 主奏 —— 锯齿状亮谐波 + 失谐 12 音分，流行/电子里的主奏就这个。
     音源增量不变（仍是失谐那 1 个）。 */
  lead: {
    harm: [0, 1, 0.7, 0.5, 0.38, 0.3, 0.24, 0.19, 0.15, 0.12, 0.09], detune: 12,
    fcut: 7, fq: 0.7, amp: [0.03, 0.12, 0.8, 0.2], trim: 1, label: "合成主奏",
    keyTrack: 0.6,
    /* 合成音色没有模态；两个低 Q 宽峰当"箱体"，避免中频染色。 */
    body: [{ f: 400, q: 0.9, gain: 2 }, { f: 1400, q: 0.8, gain: 2 }],
    /* 高音区逃生舱：主奏的高音区必须**穿过混音**（流行/电子的高音主奏本就是更亮的），
       所以高音区换一张更平的分音表，抵消 60% 跟键带来的压暗。 */
    high: { lo: 220, hi: 440, harm: [0, 1, 0.85, 0.7, 0.6, 0.5, 0.42, 0.36, 0.3, 0.26, 0.22, 0.18] },
    use: "低音区两个宽峰垫厚；中音区原样；高音区换更平的分音表，保持主奏的穿透力",
  },
  /* 人声：三件事叠在一起 —— 元音、群感、气息。
     ① 元音：低通截止本来是 6.5×f0，在 A2(110Hz) 上只有 715Hz，会把「啊」的共振峰区
        （F1≈730 / F2≈1090）整段砍掉 → 低音区只剩嗡嗡声。所以给截止一个**绝对 Hz 下限**
        （cutFloor，只对低音生效），低音区再用更长的谐波表 + F1/F2 共振峰把 700~1100Hz 撑起来。
        **高音区（A3 及以上）一个比特都不动**：lowW=0 → 用原表、不建共振峰、截止也不变。
     ② 群感 + 颤音：失谐 12 音分 + 两个速率、相位都不同步的颤音声部（vib），
        全走参数曲线自动化，**零新增音源节点**。
     ③ 气息：低电平气声，走同一个低通与包络 —— 气和嗓音是同一条「声道」出来的。
     **频谱纪律**：这条音的改动**只许往暗走**。把 2.5kHz 以上的能量抬起来（例如给 2440Hz
     的 F3 顶一个峰、或把低通全开）听感立刻变成"又亮又刺的电子味"，所以低音区那两个共振峰
     刻意**不给 F3**，气声也压在非谐能量比 1.5% 以内。 */
  choir: {
    harm: [0, 1, 0.72, 0.45, 0.22, 0.12, 0.06], detune: 12, fcut: 6.5, fq: 1.8,
    cutFloor: 1300,
    keyTrack: 0.55,
    /* 人声「啊」的四个共振峰（调研文档实测表 700/1080/2650/3500Hz，t60 0.030/0.024/0.014/
       0.010s → Q = f·t60/2.198 = 9.6/11.8/16.9/15.9；高两项 Q 收到 6 保持"宽峰"性质）。
       **2650/3500 只给 1.2/1.0dB**：低音区的低通（cutFloor 1300Hz）把它们挡在后面，
       实测 2.5kHz 以上只抬 0.3dB，守住这条音"只许往暗走"的频谱纪律。 */
    body: [{ f: 700, q: 9.6, gain: 3 }, { f: 1080, q: 11.8, gain: 2.5 },
           { f: 2650, q: 6, gain: 1.2 }, { f: 3500, q: 6, gain: 1 }],
    use: "低音区 700/1080Hz 元音共振加厚（只往暗走）；中音区原样；高音区跟键 55% → 越高越柔",
    low: {
      /* 音区过渡：f0 ≥ 220Hz（A3）→ 权重 0（高音区原样，逐位不变）；f0 ≤ 145Hz → 权重 1 */
      hi: 220, lo: 145,
      /* 低音区谐波表：前 6 项与高音区表**完全相同**（保证过渡时只有很弱的高次谐波在变），
         后面接一条缓降的尾巴 —— A2 上 700~1100Hz 就是第 7~10 次谐波，得有东西可撑。 */
      harm: [0, 1, 0.72, 0.45, 0.22, 0.12, 0.06, 0.045, 0.034, 0.026, 0.02, 0.015, 0.011],
      /* 只在低音区加增益的「啊」共振峰（绝对 Hz）。**刻意不给 F3 2440Hz**：那会把 2.5kHz
         以上的能量顶起来，听感立刻从"人声"变成"又亮又刺"。 */
      formants: [{ f: 730, q: 4, gain: 12 }, { f: 1090, q: 5, gain: 9 }],
    },
    /* 呼吸感：低电平气声（起音一口气 + 全程气息底噪）。机制走长笛那套（同一个低通 / 同一串
       共振峰 / 同一个包络），占掉音源预算里剩下的那 1 个（人声 2 → 3 = 专业档增量上限 2）。
       量级：持续电平 = 主体包络 × gain（0.15 ≈ −15dB）；起音 0.35s 内再 ×onset（3 ≈ −5dB），
       就是「ha」的那口气。 */
    /* gain 0.15 是“更像人”与“不许更亮”之间的取中值：再往上调（≈0.2）A3 的可听段
       谱斜率就会碰到上限；
       onset 3 只在起音 0.35s 内出现，不长期占用亮度预算。 */
    breath: { gain: 0.15, onset: 3, band: 1300, q: 0.7 },
    amp: [0.35, 0.28, 0.85, 0.6], trim: 1, label: "人声",
    vib: {
      /* 两个声部**速率与相位都不同步**（合唱的关键：各人颤音不同步 → 宽而柔的起伏，
         而不是整齐的波浪）。速率取 5.6/6.2Hz，幅度 ±32/±26 音分（真人独唱 ±1 半音上下）。 */
      voices: [{ rate: 5.6, cents: 32, phase: 0.0 },
               { rate: 6.2, cents: 26, phase: 2.7 }],
      wobble: 0.22, wobbleRate: 0.63,      // 颤音深度本身也有慢起伏（±22%）
      jitter: 1.2, drift: 2.5,             // 音高微抖动 σ：快（~40Hz 带限）+ 极慢漂移（音分）
      shimmer: { mid: 0.04, slow: 0.022, noiseOff: 3001 },   // 振幅抖动 σ（相对稳态增益）
      seed: 2024, noiseOff: 0,
    },
  },
  /* 长笛：气声要真的听得见。改前那层气声实测只有主体的 0.0004%（等于没有），现在 0.3%~0.8%
     —— 注意噪声走的是**这个音自己的低通**，所以带通中心要压到低音区截止（220Hz × 8 ≈ 1760Hz）
     附近，否则低音区会被整个滤掉；也正因为共用低通，气声占主体的比例上限约 1%
     （要更响就得让噪声绕开低通，那要多一个音源、导出会变慢）。谐波补到 7 次但都很弱，
     因为长笛本来就接近纯正弦。 */
  flute: {
    harm: [0, 1, 0.16, 0.07, 0.04, 0.02, 0.015, 0.01], noise: { gain: 0.9, decay: 0.45, band: 1800 },
    fcut: 8, fq: 0.7, amp: [0.09, 0.14, 0.82, 0.22], trim: 1, label: "长笛",
    keyTrack: 0.6,
    /* 长笛管体共振（Backus 表：长笛 ≈800Hz）与其第二模态 1600Hz。 */
    body: [{ f: 800, q: 3, gain: 4 }, { f: 1600, q: 2.5, gain: 3 }],
    /* 低音区的长笛**管体基本模态（800Hz）被激励得更足**：谱比中音区厚一档、尾巴拉到 10 次
       （A2 上 10 次 = 1100Hz，正好压在 800Hz 管共振的裙边上）。 */
    low: { hi: 220, lo: 145, harm: [0, 1, 0.26, 0.13, 0.085, 0.06, 0.045, 0.035, 0.028, 0.022, 0.018] },
    /* 高音区逃生舱：长笛的高音区**更亮更气声**（高音区吹口湍流占比上升）——
       换一张略丰富的分音表 + 2400Hz 低 Q 峰（这次是往亮走，所以必须走 high）。 */
    high: { lo: 220, hi: 587, harm: [0, 1, 0.22, 0.12, 0.08, 0.055, 0.04, 0.03],
            formants: [{ f: 2400, q: 1.2, gain: 2 }] },
    use: "低音区 800/1600Hz 管体共振加厚；中音区原样；高音区更亮更气声（2400Hz 低 Q 峰）",
  },
  /* ══ 本轮新增 14 个主流音色（design-a）══════════════════════════════════════════
     参数含义见文件上方注释。音区字段是**冻结 schema**：
       keyTrack  部分键盘跟踪比例（0.5~0.7；省略 = 现状 1.0）
       body      [{f,q,gain}] 固定 Hz 体共鸣（不随音高移动）
       low       {hi,lo,harm,formants} 低音区（hi ≤ 220）
       high      {lo,hi,harm,formants} 高音区逃生舱（lo ≥ 220）
       cutMax    绝对 Hz 上限（≥ 220×fcut 且 ≥ 220×fenv[0]）
       use       音区提示（“低音区/中音区/高音区/全音区”+ 2~6 字短语）
     红线：非谐性（fm 拉伸 / high 谐波表）**只给击弦/拨弦类**（musicbox / xylophone /
           kalimba / harp / harpsichord / sitar），擦弦(弦乐组)、簧片、铜管一律不加 ——
           它们的持续音因 mode-locking 是谐波的。
     预算：每音新增音源 ≤ 2（只数 oscillator / bufferSource）。 */

  /* 1. 电钢：FM 比例 14 / 指数 2.2（DX7 式 Rhodes：高比例调制器 → 敲击瞬态 + 非谐边带，
     音头亮、余音只剩接近正弦的基频，衰减 1.2~1.5s）。0.4s 测量窗落在衰减段，
     谱因高比例边带衰减极快而变得很“瘦”，与钢琴（噪声槌击 + 1/k 泛音）彻底分开。
     **非谐合法**：电钢是槌击拨片（tine）→ 击弦类，允许非谐。 */
  epiano: {
    harm: [0, 1, 0.1, 0.04, 0], fm: { ratio: 14, index: 1.8 },
    fcut: 8, fq: 0.5, amp: [0.004, 1.35, 0, 0.5], trim: 1,
    label: "电钢", use: "全音区：FM 敲击，余音清亮",
    keyTrack: 0.6, body: [{ f: 190, q: 3, gain: 5 }],
  },

  /* 2. 羽管键琴：拨弦键盘，起振极快、亮起振→暗余音（截止 22× → 1.6×）。
     低音区补足谐波表让 150~600Hz 的板体共鸣区有内容；拔弦 → 允许非谐（fs 拉伸）。 */
  harpsichord: {
    harm: [0, 1, 0.58, 0.4, 0.26, 0.18, 0.12, 0.08, 0.05, 0.03, 0.02],
    fcut: 4.5, fq: 1.0, fenv: [22, 1.6, 0.3],
    amp: [0.002, 0.95, 0, 0.22], trim: 1,
    label: "羽管键琴", use: "全音区：拨键，亮起振暗余音",
    keyTrack: 0.7, body: [{ f: 180, q: 2.5, gain: 5 }, { f: 700, q: 2, gain: 4 }],
    low: { hi: 220, lo: 110, harm: [0, 1, 0.58, 0.4, 0.26, 0.18, 0.12, 0.08, 0.05, 0.03, 0.02] },
  },

  /* 3. 爵士风琴：整数谐波（8′/4′/2⅔′/2′ 音栓）＋ 失谐 8 音分（音轮不齐 → 拍频，
     实测“起伏”维 0.263，是它与管风琴最硬的区别）。低音区按管风琴的物理做法
     **叠一个低八度层**（16′ 音栓），高音区撤掉。 */
  hammond: {
    harm: [0, 1, 0.66, 0.86, 0.4, 0.5, 0.26, 0.4, 0.16, 0.24, 0.12, 0.16, 0.09, 0.12, 0.06],
    detune: -1200,   /* 低八度音栓（16′）：整数比 -1200 音分 = 正低八度，低音区那层“叠一个低八度”就是它 */
    fcut: 10, fq: 0.5, amp: [0.012, 0.04, 0.92, 0.1], trim: 1,
    label: "爵士风琴", use: "全音区：音轮风琴，低音叠 16′",
    keyTrack: 0.6, body: [{ f: 120, q: 1.5, gain: 4 }, { f: 480, q: 1.5, gain: 3 }],
    low: {
      hi: 220, lo: 150,
      harm: [0, 1, 0.12, 0.66, 0.86, 0.4, 0.5, 0.26, 0.4, 0.16, 0.24, 0.12, 0.16, 0.09, 0.12, 0.06],
      /* 低八度音栓（16′）由 octave: -1200 的整数比 detune 层实现 —— 见上方 octave 字段注释 */
    },
  },

  /* 4. 单簧管：奇次谐波为主（只看 1/3/5/7，偶次 ≤0.06）、共振峰 1500~1700 / 3700~4300 Hz
     按 Backus 表压在低 Q 上，整体偏暗（截止 ~9×f0），起振 40~60ms。簧片 → 非谐谐波表。 */
  clarinet: {
    harm: [0, 1, 0.06, 0.72, 0.04, 0.4, 0.03, 0.22, 0.02, 0.12, 0.015],
    fcut: 9, fq: 0.8, formants: [{ f: 1600, q: 2.5, gain: 5 }, { f: 4000, q: 2, gain: 3 }],
    amp: [0.05, 0.09, 0.84, 0.14], trim: 1,
    label: "单簧管", use: "中低音区：奇次谐波簧管",
    keyTrack: 0.65, body: [{ f: 330, q: 3, gain: 6 }],
    /* 高音区：**只移共振峰、不换谐波表** —— 单簧管是簧片持续音（mode-locking 下谐波结构
       是整数倍的），给它一张非谐/换比例的 high 谐波表就是踩红线。高音区它靠“超吹到
       3 次分音”其实只变奇次权重，这里按保守做法只把 1700Hz 的峰往上挪，不动谐波比例。 */
    high: { lo: 660, hi: 1320, formants: [{ f: 1700, q: 3, gain: 5 }] },
  },

  /* 5. 双簧管：**鼻音 = 绝对 Hz 共振峰 1400 / 3000**（Backus 表）。1450Hz 的峰放在低通
     *之后*，所以 0.4s 窗里第 7 次谐波附近被抬起来 —— 这是它与其它簧片类分开的关键维。 */
  oboe: {
    harm: [0, 1, 0.5, 0.8, 0.22, 0.6, 0.13, 0.42, 0.08, 0.28, 0.05, 0.18, 0.035],
    fcut: 11, fq: 0.7, formants: [{ f: 1400, q: 4.5, gain: 10 }, { f: 3000, q: 3.5, gain: 6 }],
    amp: [0.045, 0.08, 0.86, 0.12], trim: 1,
    label: "双簧管", use: "中高音区：鼻音，1400/3000Hz",
    keyTrack: 0.6, body: [{ f: 600, q: 3, gain: 6 }],
    low: { hi: 220, lo: 145, harm: [0, 1, 0.5, 0.8, 0.22, 0.6, 0.13, 0.42, 0.08, 0.28, 0.05, 0.18, 0.035] },
    high: { lo: 660, hi: 1400, formants: [{ f: 3000, q: 4, gain: 5 }] },
  },

  /* 6. 圆号：软铜管。共振峰 400~500 Hz 靠低 Q 的 450Hz 体共鸣撑，起振 120ms 慢慢“吹开”，
     **不要 brass 那种 12×→3.5× 的急扫**（这里只做 3.4×→2.2×）。 */
  horn: {
    harm: [0, 1, 0.82, 0.6, 0.42, 0.3, 0.22, 0.15, 0.1, 0.07, 0.05, 0.035],
    fcut: 4.5, fq: 0.8, fenv: [3.4, 2.2, 0.3],
    amp: [0.12, 0.16, 0.8, 0.3], trim: 1,
    label: "圆号", use: "全音区：软铜管，起振慢",
    keyTrack: 0.55, body: [{ f: 450, q: 2.5, gain: 7 }, { f: 900, q: 2, gain: 3 }],
    low: { hi: 220, lo: 130, harm: [0, 1, 0.88, 0.7, 0.5, 0.36, 0.26, 0.18, 0.12, 0.08] },
  },

  /* 7. 竖琴：软拨弦。体共鸣照吉他 100/200/400/550 Hz（libsonare 固定模态表），
     衰减 1.0~1.4s，低音区谐波表拉长以撑起 100~550Hz 的琴体区。拨弦 → 允许非谐。 */
  harp: {
    harm: [0, 1, 0.68, 0.42, 0.3, 0.2, 0.14, 0.09, 0.06, 0.04, 0.025],
    fcut: 6, fq: 0.9, fenv: [9, 3, 0.5],
    amp: [0.003, 1.2, 0, 0.3], trim: 1,
    label: "竖琴", use: "全音区：软拨弦，余音 1.2s",
    keyTrack: 0.7, body: [{ f: 100, q: 2, gain: 5 }, { f: 200, q: 2, gain: 6 },
                          { f: 400, q: 2, gain: 5 }, { f: 550, q: 2, gain: 4 }],
    low: { hi: 220, lo: 110, harm: [0, 1, 0.72, 0.5, 0.38, 0.28, 0.2, 0.14, 0.1, 0.07, 0.05, 0.035] },
  },

  /* 8. 木琴：分音比例 [1, 3, 6.16, 10.29]（每根音条单独调音，比例固定、不随音区变），
     突出第 3 次分音。用 FM 比例 3 逼近“1 : 3”，再用高 Q 体共鸣给共鸣管
     {f0, 0.08, 1.2} + {4·f0, 0.04, 0.3} 那对峰。衰减 ~0.3s。击弦 → 允许非谐。 */
  xylophone: {
    harm: [0, 1, 0.06, 0.25],
    fm: { ratio: 3, index: 4.5 },
    fcut: 13, fq: 0.7, fenv: [13, 6, 0.12],
    amp: [0.002, 0.3, 0, 0.12], trim: 1,
    label: "木琴", use: "高音区：硬木敲击，分音 1:3",
    keyTrack: 0.6,
    body: [{ f: 220, q: 6, gain: 6 }, { f: 880, q: 4, gain: 4 }],   // 共鸣管（低音条更长）
  },

  /* 9. 八音盒：FM 比例 9.5 / 指数 3.5（钟琴式非谐边带）＋ 机械“唇”噪声（梳齿拨过滚筒的
     那一小声）。衰减 0.5~0.7s；高音区更亮（边带够得着）。击弦 → 允许非谐。 */
  musicbox: {
    harm: [0, 1, 0.12, 0.06],
    fm: { ratio: 9.5, index: 3.5 }, noise: { gain: 0.5, decay: 0.02, band: 5200 },
    fcut: 14, fq: 0.6, amp: [0.002, 0.6, 0, 0.2], trim: 1,
    label: "八音盒", use: "高音区：FM 梳齿，带机械噪声",
    keyTrack: 0.6, body: [{ f: 1400, q: 4, gain: 4 }],
  },

  /* 10. 卡林巴：基频很强、高次弱（拇指琴的金属舌片几乎只有基频），起振软（40ms，指甲挑起
     不是敲），衰减 0.9~1.2s。用高 Q 体共鸣在 f0 上做木箱腔的共振峰。
     ⚠ 实测撞车风险最高的一条：它与长笛（上谐/基频 0.337）、人声都落在“基频强”区域，
     最后靠 fcut 把上谐压到远低于长笛、再靠“起伏+包络”拉开（见 report.md 实测表）。 */
  kalimba: {
    harm: [0, 1, 0.2, 0.09, 0.04, 0.02],
    fcut: 3, fq: 1.4, fenv: [5, 2.2, 0.3],
    amp: [0.04, 1.0, 0, 0.25], trim: 1,
    label: "卡林巴", use: "全音区：拇指琴，只留基频",
    keyTrack: 0.7, body: [{ f: 240, q: 4, gain: 5 }],
    low: { hi: 220, lo: 130, harm: [0, 1, 0.26, 0.13, 0.06, 0.03, 0.015] },
  },

  /* 11. 手风琴：双簧失谐 musette 14 音分（两排簧片刻意调不准 → 明显拍频），簧片谐波
     （奇偶都有、1/k 缓降）。低音区叠低八度层（左手贝斯排）。簧片 → 非谐谐波表。 */
  accordion: {
    harm: [0, 1, 0.7, 0.5, 0.35, 0.24, 0.16, 0.11, 0.07, 0.05, 0.03],
    detune: 14, fcut: 8, fq: 0.7, fenv: [9, 7, 0.11],
    amp: [0.035, 0.1, 0.84, 0.16], trim: 1,
    label: "手风琴", use: "全音区：双簧 musette 拍频",
    keyTrack: 0.6, body: [{ f: 600, q: 2, gain: 4 }, { f: 1200, q: 2, gain: 3 }],
    low: {
      hi: 220, lo: 150,
      harm: [0, 1, 0.12, 0.7, 0.5, 0.35, 0.24, 0.16, 0.11, 0.07, 0.05, 0.03],
    },
  },

  /* 12. 尺八：气声明显、谐波很弱（fcut 3 = 只放行前三次）、共振峰参照长笛约 800 Hz，
     起振 80~120ms（吹口要“找音”）。气声走自己的带通 700Hz，落在低通之前，所以 A3 的
     0.4s 窗里仍量得到宽带成分（实测噪声维 0.53，与长笛的 0.0000 形成硬区分）。 */
  shakuhachi: {
    harm: [0, 1, 0.05, 0.03, 0.42, 0.02, 0.28, 0.01, 0.22, 0.01, 0.14, 0.01, 0.1],
    noise: { gain: 2.0, decay: 0.85, band: 1160 },
    /* 长笛式 800Hz 峰只留很低（-1dB 量级），真正给音色定形的是竹管的 **1.4kHz / 3kHz 两个峰**：
       它们让第 4/6/8/10 次谐波整片站起来（实测上谐/基频 0.93，长笛只有 0.337），
       同时第 2/3 次被刻意压到 0.05/0.03 —— 这就是它与长笛（平滑 1/k 缓降）的硬区别。
       气声走自己的带通 1160Hz、衰减 0.85s，0.4s 测量窗里仍在，宽带噪声比 ≈0.6。 */
    fcut: 4.5, fq: 0.6,
    formants: [{ f: 800, q: 1.2, gain: 1 }, { f: 1400, q: 1.5, gain: 9 },
               { f: 3000, q: 1.5, gain: 7 }],
    amp: [0.1, 0.16, 0.8, 0.22], trim: 1,
    label: "尺八", use: "全音区：气声竹笛，起振 100ms",
    keyTrack: 0.6, body: [{ f: 800, q: 1.5, gain: 5 }],
    low: { hi: 220, lo: 130, harm: [0, 1, 0.2, 0.1, 0.04] },
  },

  /* 13. 西塔琴：拨弦 + 强琴体共振峰。照小提琴桥丘 2350/2750Hz 给峰，再补 500/1200Hz。
     0.4s 窗落在奏鸣弦的持续嗡嗡段（低音区才有、加长衰减 2.2s），与竖琴/拨弦分开。
     拨弦 → 允许非谐（high 谐波表给 3 个峰）。 */
  sitar: {
    harm: [0, 1, 0.75, 0.55, 0.42, 0.3, 0.22, 0.2, 0.16, 0.14, 0.12, 0.1, 0.09, 0.08, 0.07],
    fcut: 9, fq: 1.2, fenv: [12, 3, 0.45],
    formants: [{ f: 500, q: 3, gain: 6 }, { f: 1200, q: 3, gain: 5 },
               { f: 2350, q: 5, gain: 7 }, { f: 2750, q: 5, gain: 6 }],
    amp: [0.003, 0.9, 0.05, 0.3], trim: 1,
    label: "西塔琴", use: "全音区：拨弦+桥丘共振",
    keyTrack: 0.65, body: [{ f: 500, q: 2.5, gain: 5 }, { f: 2350, q: 4, gain: 5 }],
    low: {
      hi: 220, lo: 110,
      harm: [0, 1, 0.78, 0.6, 0.48, 0.36, 0.28, 0.24, 0.2, 0.17, 0.14, 0.12, 0.1, 0.09, 0.08],
    },
    high: {
      lo: 660, hi: 1400,
      harm: [0, 1, 0.78, 0.58, 0.46, 0.34, 0.26, 0.22, 0.18, 0.15, 0.13, 0.11, 0.1, 0.09, 0.08],
      formants: [{ f: 2750, q: 5, gain: 6 }],
    },
  },

  /* 14. 酸性贝斯：锯齿谐波（1/k 到第 12 次）+ 高 Q 低通大幅下扫
     fq 8、fenv 17 → 2.2、0.4s 扫完（acid 那条“呜”）。每音只有 1 个音源。 */
  acidbass: {
    harm: [0, 1, 0.5, 0.33, 0.25, 0.2, 0.17, 0.14, 0.13, 0.11, 0.1, 0.09, 0.08],
    fcut: 5, fq: 8, fenv: [17, 2.2, 0.4],
    amp: [0.006, 0.55, 0.3, 0.14], trim: 1,
    label: "酸性贝斯", use: "低音区：锯齿，8µ 低通下扫",
    keyTrack: 0.6, body: [{ f: 90, q: 3, gain: 5 }, { f: 450, q: 3, gain: 4 }],
    cutMax: 4200,   // ≥ 220×fcut(5)=1100，≥ 220×fenv[0](17)=3740
    low: { hi: 220, lo: 130, harm: [0, 1, 0.5, 0.45, 0.35, 0.3, 0.25, 0.22, 0.2, 0.18, 0.16, 0.14] },
  },
};

/* 三档音色集。高档 ⊃ 低档，保证换档不会让已有乐谱失效。
   档位**只决定给模型的词表大小**，不决定导出耗时（耗时看乐谱实际用到哪些音色）。 */
const TIMBRE_TIERS = {
  basic: ["sine", "triangle", "sawtooth", "square"],
  /* 增强档 = 基础 4 + 具名 14（原专业档那 14 个：管风琴 … 长笛）。 */
  enhanced: ["sine", "triangle", "sawtooth", "square",
             "organ", "brass", "strings", "pluck", "marimba", "pad", "reed", "bass",
             "bell", "piano", "metal", "lead", "choir", "flute"],
  /* 专业档 = 增强档 18 + 新增 14 个主流音色（键盘 / 管弦 / 打击 / 世界 / 电子）。 */
  pro: ["sine", "triangle", "sawtooth", "square",
        "organ", "brass", "strings", "pluck", "marimba", "pad", "reed", "bass",
        "bell", "piano", "metal", "lead", "choir", "flute",
        "epiano", "harpsichord", "hammond", "clarinet", "oboe", "horn", "harp",
        "xylophone", "musicbox", "kalimba", "accordion", "shakuhachi", "sitar", "acidbass"],
};
const TIMBRE_TIER_LABELS = { basic: "基础音色集", enhanced: "增强音色集", pro: "专业音色集" };
const DEFAULT_TIER = "basic";

/** 某个名字是否已知音色（跨所有档）。用于导入/校验时宽容处理。 */
function isKnownTimbre(name) { return Object.prototype.hasOwnProperty.call(TIMBRES, name); }
/** 名字所属的最低档位（用于提示词里告诉模型这个音色哪档才有）。 */
function timbreTierOf(name) {
  if (TIMBRE_TIERS.basic.includes(name)) return "basic";
  if (TIMBRE_TIERS.enhanced.includes(name)) return "enhanced";
  if (TIMBRE_TIERS.pro.includes(name)) return "pro";
  return null;
}
/** 音色的中文名，给图例与提示词用。 */
function timbreLabel(name) {
  const t = TIMBRES[name];
  return t && t.label ? t.label : name;
}
/** 某档可用音色的「名字 + 用途」，供提示词动态生成枚举表。 */
function timbreNames(tier) {
  const list = TIMBRE_TIERS[tier] || TIMBRE_TIERS[DEFAULT_TIER];
  return list.map((n) => {
    const spec = TIMBRES[n] || {};
    const out = { name: n, label: timbreLabel(n) };
    if (spec.use) out.use = spec.use;   // 音区提示：只有具名音色有（基础 4 个波形没有）
    return out;
  });
}

/* ── 长篇（1/3/5 分钟）的边界 ─────────────────────────────────────────── */
/**
 * 长篇与短篇的关键差别：短篇把速度交给模型，长篇**由我们定速**。
 * 因为时长 = 小节数 × 每小节拍数 × 60/bpm，若 bpm 由模型决定，我们事先无法算出该写多少小节，
 * 时长就精确不了。故长篇先按「速度倾向」取一个代表值，反推小节数，再把两个数都钉死告诉模型。
 */
const LONG_SECONDS = { "1": 60, "3": 180, "5": 300 };
const LONG_BPM = { auto: 96, slow: 72, mid: 96, fast: 132 };
const MAX_BARS = 240;          // 6 分钟以内，留余量
const MAX_TRACKS = 8;          // 音轨上限。试过放到 12，实测声部一多就糊成一团、反而更差，故维持 8。
const MAX_NOTES = 6000;        // 原 900，长篇需要上千
const MAX_PERC = 1500;         // 原 200
const MAX_LAYERS = 16;         // sfx 音层，原 12
const MAX_SECTIONS = 24;       // 曲式段落数上限
const LONG_MAX_ROUNDS = 3;     // 被截断时最多续写几次
const TAIL_SLACK_BEATS = 1;    // 末尾延长音探出小节线多少拍之内，不算新的一小节

/* ── 拍号与律动 ───────────────────────────────────────────────────────── */
/**
 * 时间轴的单位永远是「拍」＝ 60/bpm 秒；一小节 = 每小节拍数 × 60/bpm 秒。
 * 所以每个拍号必须同时说明「这里的拍是哪种音符」，否则同一个 BPM 数字会差好几倍：
 *   二连分的档，拍 = 四分音符（7/8 例外，拍 = 八分音符）；
 *   三连分的档是复合拍：拍 = 附点四分（一个大拍 = 三个八分），故 6/8 一小节只有 2 拍。
 * subdiv 只进提示词与记谱习惯，**不参与任何时长计算**。
 */
const METERS = {
  "4/4": { beats: 4, subdiv: 2, note: "quarter" },
  "3/4": { beats: 3, subdiv: 2, note: "quarter" },
  "2/4": { beats: 2, subdiv: 2, note: "quarter" },
  "5/4": { beats: 5, subdiv: 2, note: "quarter" },
  "7/8": { beats: 7, subdiv: 2, note: "eighth" },
  "6/8": { beats: 2, subdiv: 3, note: "dotted quarter" },
  "9/8": { beats: 3, subdiv: 3, note: "dotted quarter" },
  "12/8": { beats: 4, subdiv: 3, note: "dotted quarter" },
};
const DEFAULT_METER = "4/4";
/* 拍号下拉的「交给模型」档：拍号由模型从 METERS 清单里选，引擎认它输出的 meter。
   它是**默认档**（与「速度倾向」的「交给模型」对称）。 */
const AUTO_METER = "auto";

/**
 * 律动。swing 是纯时间映射：后半拍的落点 = span × r/(1+r) 拍（r 是「长:短」比例）；
 * halftime 不是时间映射，而是把军鼓/拍手并到小节内第 3 拍（重音减半）；
 * genre 只在提示词里要求模型写曲风标志性鼓型，引擎不动。
 */
const GROOVES = {
  straight: {},
  swing8_2: { swing: { span: 1, ratio: 2 } },
  swing8_3: { swing: { span: 1, ratio: 3 } },
  swing16_12: { swing: { span: 0.5, ratio: 1.2 } },
  swing16_15: { swing: { span: 0.5, ratio: 1.5 } },
  halftime: { halftime: true },
  genre: { genre: true },
};
const DEFAULT_GROOVE = "straight";

/** 乐谱的拍号。老乐谱、导入的乐谱没有这个字段时按 4/4（改动前的行为）。 */
function meterOf(s) {
  return s && METERS[s.meter] ? s.meter : DEFAULT_METER;
}
/** 一小节几拍。全文件只从这里读这个数，不再有写死的 4。 */
function beatsOf(s) {
  return METERS[meterOf(s)].beats;
}
/** 每拍内分几份（2 = 二连分，3 = 三连分/复合拍）。 */
function subdivOf(s) {
  return METERS[meterOf(s)].subdiv;
}
/** 提示词里给模型的拍号清单。每档都写明每小节拍数与拍内份数，模型才知道怎么写。 */
function meterMenuText() {
  return Object.keys(METERS).map((m) => {
    const x = METERS[m];
    return m + " (" + x.beats + " beats/bar" + (x.subdiv === 3 ? ", each beat = three eighths" : "") + ")";
  }).join(", ");
}

/** 小节数上限。上限的本意是「总拍数」（时长、内存与卷帘图可读性），所以按拍号折算，
    并且**向上取整**保证至少 960 拍（7/8 用 round 会得到 137×7=959 拍，5 分钟 + 快速度时被早夹一格）：
    4/4 → 240 小节；2/4 → 480；7/8 → 138。不折算的话 2/4 走 132 BPM 的 5 分钟曲需要 330 小节，
    会被 240 的旧上限截断成 3 秒的残曲。 */
function maxBarsOf(beatsPerBar) {
  return Math.ceil((MAX_BARS * 4) / beatsPerBar);
}

/** 速度档位的中文名（用户可见的提示里用，避免把英文提示词串原样塞进中文句子）。 */
function tempoLabel(key) {
  return key === "slow" ? "舒缓 60–80" : key === "mid" ? "中速 84–110" : key === "fast" ? "流动 116–150" : "";
}

/** 速度档位 → [下限, 上限]；「交给模型」与自定义没有档位范围，返回 null。 */
function tempoRange(key) {
  return key === "slow" ? [60, 80] : key === "mid" ? [84, 110] : key === "fast" ? [116, 150] : null;
}

/** 这个 BPM 是否落在选定档位之外。为什么要有它：拍号选「交给模型」时，速度由模型写的小节数
    与目标时长反推，可能落在用户选的档位之外（实测模型照抄示例的 24 小节 → 96 BPM，而用户选的是
    「流动 116–150」），那时时长是精确的、偏差检查不会响 —— 必须单独把这件事说出来。 */
function bpmOutsideTier(bpm, range) {
  return !!range && (bpm < range[0] || bpm > range[1]);
}

/** 速度倾向 / 自定义 BPM → 给模型的一句速度说明。buildPrompt 与长篇的 readLength 共用同一份文案。 */
function tempoRangeText(tempo, customBpm) {
  if (customBpm) return "exactly " + customBpm + " BPM";
  return tempo === "slow" ? "slow, 60-80 BPM" : tempo === "mid" ? "moderate, 84-110 BPM"
    : tempo === "fast" ? "flowing, 116-150 BPM" : "your choice, 60-150 BPM";
}

/** 这个拍号下摇摆是否不生效：复合拍每拍三连分，摇摆要找的「后半拍」位本来是空的。
    applyGroove 的静默、提示词里那句「写直的细分」是否下发、以及长篇的警告都以此为准。 */
function meterBlocksSwing(meter, groove) {
  return !!(GROOVES[groove] && GROOVES[groove].swing && METERS[meter] && METERS[meter].subdiv === 3);
}

/** 修订时的律动提示（空串 = 无需提示）。
    判据必须与**上一版乐谱**比：normalizeScore 写回的 score.groove 就是本次传进去的下拉值，
    跟自己比永远相等 —— 第一轮的实现正是这样变成死代码的（42 组 0 触发，被独立复验抓到）。
    而且只在**上一版本身就是摇摆**时才有话说：摇摆过的起点不可逆，换成别的档退不回去。
    反方向（上一版不是摇摆 → 这次换摇摆）是能正常生效的，提示反而误导 —— 实测 42 组换档里有 30 组
    属于这种误报（例如「直拍 → 摇摆 8 分 2:1」其实生效，文案却说不会再挪）。 */
function grooveSwitchWarning(prevGroove, pickedGroove) {
  const prev = GROOVES[prevGroove] ? prevGroove : DEFAULT_GROOVE;
  const picked = GROOVES[pickedGroove] ? pickedGroove : DEFAULT_GROOVE;
  if (prev === picked) return "";
  /* 两类律动都是**有损、不可逆**的，都该说：
     ① 摇摆：坐标被挪过，换档要么在已摇摆的坐标之上再叠加新偏移，要么不再改动 —— 但退不回去。
        文案只说「不会退回去 / 只会叠加」，不说「一点都不会变」（后者在 71% 的换档里不成立）。
     ② 半速感：把同一小节的军鼓/拍手并成 1 个（事件被删掉），换档不会把那一个补回来 ——
        比摇摆更难自查（摇摆是坐标斜移、卷帘图看得见；半速感是少了一个事件）。 */
  if (GROOVES[prev].swing) {
    return "律动档位从「" + prev + "」改成「" + picked + "」：上一版谱面已经是摇摆过的坐标（摇摆不可逆），"
      + "新档只会在已摇摆的坐标之上叠加新的偏移或不再改动，不会把上一版的摇摆退回去。想听纯粹的新律动，请重新「落笔」写一首。";
  }
  if (GROOVES[prev].halftime) {
    /* 措辞要同时覆盖两种情形：同一小节有多个军鼓/拍手时会**合并成一个**，本来就只有一个时只是**挪位**
       （被复验指出的过窄措辞）。所以这里说的是「每小节只留一次、落第 3 拍」这个改写动作本身不可逆。 */
    return "律动档位从「" + prev + "」改成「" + picked + "」：上一版半速感改写过鼓点（军鼓/拍手每小节只留一次、落第 3 拍："
      + "同一小节多个会合并成一个，本来就单个的会被挪位），这步不可逆 —— 换档不会把它改回去，鼓型仍是半速感那套。"
      + "想换回原鼓型，请重新「落笔」写一首。";
  }
  return "";
}

/** 提示词里怎么描述拍号。4/4 的输出必须与改动前逐字相同（"4 beats per bar"）。 */
function beatsPerBarText(meter) {
  const m = METERS[meter] || METERS[DEFAULT_METER];
  if (m.subdiv === 3) return m.beats + " beats per bar (each beat is a dotted quarter = three eighth notes)";
  if (m.note === "eighth") return m.beats + " eighth-note beats per bar";
  return m.beats + " beats per bar";
}

/** 复合拍的写法提示（拍内三连分）。二连分的拍号返回空串，默认路径提示词不变。 */
function subdivLine(meter) {
  const m = METERS[meter] || METERS[DEFAULT_METER];
  if (m.subdiv !== 3) return "";
  return "- The beat divides into three equal eighths (compound meter): write startBeat values such as"
    + " 0.333, 0.667, 1.333, and let the dotted-quarter beat carry the pulse.\n";
}

/** 律动写进提示词的那几句。直拍返回空串 —— 默认路径的提示词一个字节都不变。 */
function grooveLine(groove, meter) {
  const g = GROOVES[groove] || {};
  if (g.swing) {
    // 复合拍下摇摆不生效，就别再要求模型「写直的细分」—— 那与三连分指令自相矛盾。
    if (meterBlocksSwing(meter, groove)) return "";
    return "- Write STRAIGHT subdivisions: no swing feel, no triplets. The swing feel is applied afterwards,"
      + " so notate the notes evenly on the grid.\n";
  }
  if (g.halftime) {
    return "- Use a HALF-TIME feel: one backbeat per bar (snare/clap on beat 3), a sparse kick on beats 1 and 3,"
      + " chords changing every bar or two, melody in long notes. Hi-hats may stay busy.\n";
  }
  if (g.genre) {
    return "- Write the signature drum pattern of the genre the idea describes (e.g. reggae one drop with the"
      + " snare on beat 3 of every bar, a Latin/bossa clave, or a house four-on-the-floor kick).\n";
  }
  return "";
}

/**
 * 把律动套到谱面上。只作用于旋律模式。
 * 摇摆：只把「后半拍」上的起点往后挪 span×r/(1+r) —— 挪过之后不再满足后半拍条件，故**幂等**；
 *       正拍不动；音轨与打击乐都套。
 * 半速感：军鼓/拍手每小节只留一次、落小节内第 3 拍（小节不足 3 拍时落最后一拍），同小节取最大力度；
 *         底鼓与踩镲不动，trap 的 16 分踩镲因此保留。
 */
function applyGroove(score, groove) {
  const g = GROOVES[groove] || {};
  if (!score || score.mode !== "melody") return score;
  /* 复合拍（每拍三连分）下摇摆**不生效**：它要找的「后半拍」在这套网格上本来是空的，
     真挪了反而会把 x.5 上的音堆到 x.667 的三连音位上（同轨同 start，一个盖住另一个），
     整条踩镲也会离开三连音网格。独立复验实测 6/8：0, 0.5, 0.667, 1 → 0, 0.667, 0.667, 1。
     所以这里直接返回 —— 「不生效」必须是真不生效，而不是把音挪歪。 */
  if (meterBlocksSwing(meterOf(score), groove)) return score;
  if (g.swing) {
    const span = g.swing.span, off = (span * g.swing.ratio) / (1 + g.swing.ratio);
    const move = (b) => {
      const local = b - Math.floor(b / span) * span;
      return Math.abs(local - span / 2) < 1e-6 ? b - span / 2 + off : b;
    };
    for (const t of score.tracks) {
      for (const n of t.notes) n.start = move(n.start);
      t.notes.sort((a, b) => a.start - b.start);
    }
    for (const p of score.percussion) p.beat = move(p.beat);
    score.percussion.sort((a, b) => a.beat - b.beat);
  }
  if (g.halftime) {
    const bpb = beatsOf(score), kept = [], done = {};
    const end = score.bars * bpb;
    for (const p of score.percussion) {
      if (p.kind !== "snare" && p.kind !== "clap") { kept.push(p); continue; }
      // 落在时间轴末尾边界（beat === 小节数 × 每小节拍数）的那一下不属于任何小节：
      // 硬并进「最后一小节的第 3 拍」会把它挪出轴外 —— 导出听得见、播放窗口却跳过它（实测可达）。
      if (p.beat >= end) { kept.push(p); continue; }
      const bar = Math.floor(p.beat / bpb);
      if (done[bar]) {
        done[bar].vel = Math.max(done[bar].vel, p.vel);
        // 同一小节既有拍手又有军鼓时保留军鼓 —— 它是 backbeat 的主角，别被先到者吃掉。
        if (done[bar].kind === "clap" && p.kind === "snare") done[bar].kind = "snare";
        continue;
      }
      done[bar] = { kind: p.kind, beat: bar * bpb + Math.min(2, bpb - 1), vel: p.vel };
      kept.push(done[bar]);
    }
    kept.sort((a, b) => a.beat - b.beat);
    score.percussion = kept;
  }
  return score;
}

/* 总线余量：压进音轨求和之后的固定衰减，给后面的软削波留头部空间。
   只在这里减一次——**调用方一律传「用户音量本身」**。
   曾经的写法是 buildGraph 内乘一次 0.9、startPlayback 又传 state.volume*0.9，
   于是播放实际是 0.9²=0.81 倍，而音量条那条路径只乘一次 0.9，两条路径对不上；
   导出又恒传 volume=1，完全忽略音量条。实测播放比导出低约 1.7 dB（音量条 82% 时），
   去标量后残差 1.2%（压缩器与软削波的非线性所致）。现在把 0.9 收拢成一个常量，
   三条路径（首次播放 / 音量条 / 导出的 100% 基准）就自洽了。 */
const HEADROOM = 0.9;

/** 当前选中的音色集档位。越高档，给模型开放的音色词表越大。 */
function selectedTier() {
  const el = $("timbreset");
  const v = el ? el.value : DEFAULT_TIER;
  return TIMBRE_TIERS[v] ? v : DEFAULT_TIER;
}

/** 切换档位。给「导入乐谱后自动抬档」与验收脚本用。 */
function setTimbreTier(tier) {
  if (!TIMBRE_TIERS[tier]) return false;
  const el = $("timbreset");
  if (el) el.value = tier;
  return true;
}

/** 让当前档位至少能覆盖这些音色 —— 导入别处的乐谱时用，
    否则 UI 会显示低档、乐谱却含高档音色，改一次就全被降级。
    取所有出现过的音色所需档位的**最高**者。返回是否真的抬了档。 */
function raiseTierToCover(waves) {
  const order = ["basic", "enhanced", "pro"];
  let need = 0;
  for (const w of waves || []) {
    const t = timbreTierOf(w);
    if (t) need = Math.max(need, order.indexOf(t));
  }
  const cur = order.indexOf(selectedTier());
  if (need > cur) return setTimbreTier(order[need]);
  return false;
}

/** 从下拉读拍号/律动/自定义速度。非法值一律回默认，不抛错。 */
function readMeter() {
  const el = $("meter");
  if (el && el.value === AUTO_METER) return AUTO_METER;
  return el && METERS[el.value] ? el.value : DEFAULT_METER;
}
function readGroove() {
  const el = $("groove");
  return el && GROOVES[el.value] ? el.value : DEFAULT_GROOVE;
}
/** 自定义 BPM：只有选中「自定义」才用输入框的值；否则返回 null（交给档位代表值/模型）。 */
function readCustomBpm() {
  if ($("tempo").value !== "custom") return null;
  return Math.round(clamp(numOr($("bpm").value, 96), 40, 200));
}

/** 把「篇幅」下拉的值翻译成实际的小节数/时长。 */
/**
 * 长篇的「小节数 + BPM」方案。
 * 自定义 BPM：速度是用户钉死的，不可能再回推 —— 整除搜索在这里零收益、纯有害
 *   （它只会把小节数推离最接近的值；独立复验实测 3864 组里 1343 组比朴素取整更差、0 组更好）。
 *   所以直接取整，下限放宽到 1 小节（旧的 8 小节下限在慢速 + 短篇下会把时长顶到 +40%）。
 * 否则：按代表速度反推整数小节数，再回推整数 BPM 把时长锁到秒。精确的条件是
 *   bpm = 小节数 × 拍数 ÷ perMin 为整数 —— 旧代码只在 4/4 下天然满足
 *   （24 小节 × 4 ÷ 1 = 96），换成 5/4、7/8 后 1 分钟会差 1~2%（实测 5/4 59.375 秒、7/8 61.25 秒）。
 *   做法：在理想小节数两侧找最近的、满足整除的小节数（最多挪 perMin−1 小节），再回推 BPM；
 *   代价是 BPM 偏离速度档代表值最多约一个小节（实测 7/8 的 5 分钟 72→77，仍在「舒缓 60–80」内）。
 */
function longPlan(beatsPerBar, secs, wanted, customBpm) {
  if (customBpm) {
    return { bars: clamp(Math.round((secs * customBpm) / (60 * beatsPerBar)), 1, maxBarsOf(beatsPerBar)), bpm: customBpm, custom: true };
  }
  const perMin = secs / 60;                                   // 1 分钟 = 1、3 分钟 = 3、5 分钟 = 5
  const maxBars = maxBarsOf(beatsPerBar);
  const ideal = clamp(Math.round((secs * wanted) / (60 * beatsPerBar)), 8, maxBars);
  let bars = 0;
  for (let d = 0; d <= 10 && !bars; d++) {
    for (const b of [ideal - d, ideal + d]) {
      if (b >= 8 && b <= maxBars && (b * beatsPerBar) % perMin === 0) { bars = b; break; }
    }
  }
  return { bars, bpm: Math.round((bars * beatsPerBar * 60) / secs), custom: false };
}

function readLength() {
  const v = $("bars").value;
  const meter = readMeter();
  const autoMeter = meter === AUTO_METER;
  // 拍号交给模型时我们还不知道「一小节几拍」，先按 4/4 备一套兜底（下面说明为什么必须有兜底）。
  const beatsPerBar = autoMeter ? METERS[DEFAULT_METER].beats : METERS[meter].beats;
  const groove = readGroove();
  const m = /^long:([135])$/.exec(v);
  if (!m) {
    const b = parseInt(v, 10);
    return { long: false, bars: clamp(isFinite(b) ? b : 4, 1, 16), secs: null, bpm: null, meter, beatsPerBar, groove, autoMeter };
  }
  const secs = LONG_SECONDS[m[1]];
  const tempoKey = $("tempo").value;
  const custom = readCustomBpm();
  const wanted = custom || LONG_BPM[tempoKey] || 96;
  /* 拍号交给模型时我们事先不知道「一小节几拍」，反推不出小节数 —— 改由模型按 buildLongPrompt
     的公式自己算，随后由 pinLongDuration 认它的拍号、把时长锁回来。但这里**仍然给一套有限的兜底
     数字**：① 音效根本没有拍号概念，走的是同一套续写/合并逻辑；② 旋律路径万一定不到模型给的数，
     下游也不该拿到 null —— 第一版就是 null 让「音效 + 交给模型 + 回复截断」的续写提示词出现
     NaN（独立复验抓到）。 */
  const plan = longPlan(beatsPerBar, secs, wanted, custom);
  return {
    long: true, secs, bars: plan.bars, bpm: plan.bpm, custom: plan.custom,
    meter, beatsPerBar, groove, autoMeter, tempoKey, tempoRange: tempoRange(tempoKey),
    // 用户明确选过速度（自定义 BPM 或某一档）时，把这个要求原样交给模型，别让它自己拍
    tempoAsk: (custom || tempoKey !== "auto") ? tempoRangeText(tempoKey, custom) : "",
  };
}

function clamp(v, a, b) { return v < a ? a : v > b ? b : v; }
function numOr(v, d) {
  const x = typeof v === "string" ? parseFloat(v) : v;
  return typeof x === "number" && isFinite(x) ? x : d;
}
function pitchToMidi(p) {
  if (typeof p === "number" && isFinite(p)) return Math.round(p);
  if (typeof p !== "string") return null;
  const m = p.trim().match(/^([A-Ga-g])\s*([#b♯♭]?)\s*(-?\d{1,2})$/);
  if (!m) return null;
  let acc = 0;
  if (m[2] === "#" || m[2] === "♯") acc = 1;
  else if (m[2] === "b" || m[2] === "♭") acc = -1;
  return (parseInt(m[3], 10) + 1) * 12 + NOTE_OFFSETS[m[1].toLowerCase()] + acc;
}
function midiToFreq(m) { return 440 * Math.pow(2, (m - 69) / 12); }
function midiToName(m) {
  const names = ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"];
  return names[((m % 12) + 12) % 12] + (Math.floor(m / 12) - 1);
}

/** 已写完的最后一个拍点（音符末端与鼓点取最大）。纯函数，放在引擎段里便于离线验收。 */
function rawEndBeat(raw) {
  let end = 0;
  for (const t of (Array.isArray(raw && raw.tracks) ? raw.tracks : [])) {
    for (const n of (Array.isArray(t && t.notes) ? t.notes : [])) {
      if (Array.isArray(n) && isFinite(n[1])) end = Math.max(end, n[1] + (isFinite(n[2]) ? n[2] : 0));
    }
  }
  for (const p of (Array.isArray(raw && raw.percussion) ? raw.percussion : [])) {
    if (Array.isArray(p) && isFinite(p[1])) end = Math.max(end, p[1] + 0.5);
  }
  return end;
}

/**
 * 长篇 + 拍号「交给模型」：小节数、速度都是模型自己算的（见 buildLongPrompt 的公式）。
 * 我们只做一件事 —— 认下它的拍号与小节数，把 BPM 微调到最接近的整数，让时长回到目标值。
 * 为什么要微调：小节数必须是整数、BPM 也必须取整，两者与目标时长总有微小矛盾；
 * 1 分钟档能精确命中，3/5 分钟档最多差 1 个 BPM（实测最坏 1.01%，见验收台 [11]）。
 * 模型漏给 bars 时按它写到的最后一个音反推小节数，避免下游拿到 NaN。
 */
function pinLongDuration(raw, secs, fixedBpm) {
  if (!raw || typeof raw !== "object") return null;
  const meter = typeof raw.meter === "string" && METERS[raw.meter] ? raw.meter : DEFAULT_METER;
  const beats = METERS[meter].beats;
  const maxBars = maxBarsOf(beats);
  let bars = Math.round(clamp(numOr(raw.bars, 0), 0, maxBars));
  if (!bars) bars = Math.max(1, Math.min(maxBars, Math.ceil(rawEndBeat(raw) / beats)));
  // 用户填了自定义 BPM 就钉死它（他明说了速度），时长偏差由调用方如实报出；否则按目标时长回推。
  const bpm = fixedBpm ? Math.round(clamp(fixedBpm, 40, 200)) : Math.round(clamp((bars * beats * 60) / secs, 40, 200));
  raw.meter = meter;
  raw.bars = bars;
  raw.bpm = bpm;
  return { meter, beats, bars, bpm };
}

/**
 * 把模型返回的任意结构整形成可信的乐谱。模型会犯错：缺字段、超范围、
 * 字符串数字、音名写成 MIDI 号。这里全部收敛到合法区间，并记录警告。
 */
function normalizeScore(raw, forcedMode, tier, forcedMeter, groove) {
  const warn = [];
  if (!raw || typeof raw !== "object") return { score: null, warn: ["模型未返回可解析的对象"] };

  const mode = forcedMode || (raw.mode === "sfx" || Array.isArray(raw.layers) ? "sfx" : "melody");
  // 拍号由界面钉死；导入别处的乐谱时认它自带的，认不出就按 4/4（改动前的行为）。
  // 只认字符串：模型偶尔把拍号写成数组（["3/4"]），JS 的属性查找会隐式转字符串放它过去，
  // 结果 score.meter 存成数组、带进导出的 JSON。这里直接挡掉。
  const rawMeter = typeof raw.meter === "string" ? raw.meter : "";
  const meter = METERS[forcedMeter] ? forcedMeter : (METERS[rawMeter] ? rawMeter : DEFAULT_METER);
  const bpb = METERS[meter].beats;
  const score = {
    title: typeof raw.title === "string" ? raw.title.trim().slice(0, 28) : "",
    mood: typeof raw.mood === "string" ? raw.mood.trim().slice(0, 48) : "",
    mode,
    bpm: Math.round(clamp(numOr(raw.bpm, 84), 40, 200)),
    bars: Math.round(clamp(numOr(raw.bars, 4), 1, maxBarsOf(bpb))),
    meter,
    tracks: [],
    percussion: [],
    layers: [],
    sections: [],
    fx: { reverb: clamp(numOr(raw.fx && raw.fx.reverb, mode === "sfx" ? 0.46 : 0.34), 0, 0.9) },
  };

  // 曲式段落：模型给就收，用于卷帘图上画结构条、也算进修订提示词
  if (Array.isArray(raw.sections)) {
    for (const rs of raw.sections.slice(0, MAX_SECTIONS)) {
      if (!rs || typeof rs !== "object") continue;
      const from = Math.round(numOr(rs.fromBar, null) || 0);
      const to = Math.round(numOr(rs.toBar, null) || 0);
      if (from < 1 || to < from) continue;
      score.sections.push({
        label: (typeof rs.label === "string" ? rs.label : "").trim().slice(0, 6) || "·",
        role: (typeof rs.role === "string" ? rs.role : "").trim().slice(0, 14),
        fromBar: clamp(from, 1, MAX_BARS),
        toBar: clamp(to, from, MAX_BARS),
      });
    }
    score.sections.sort((a, b) => a.fromBar - b.fromBar);
  }

  if (mode === "melody") {
    const rawTracks = Array.isArray(raw.tracks) ? raw.tracks : [];
    if (!rawTracks.length) warn.push("模型没有给出任何音轨");
    let total = 0;
    for (const rt of rawTracks.slice(0, MAX_TRACKS)) {
      if (!rt || typeof rt !== "object") continue;
      let wave = typeof rt.wave === "string" ? rt.wave.toLowerCase().trim() : "";
      /* 校验口径：**接受音色库全集**，但对"超出本次所选档位"的名字给一句提示。
         为什么不直接按档位拒绝——导入别处的乐谱、或换档后重跑修订时，
         数据不该因为档位口径不同而丢失。档位只决定"给模型开放到哪"，不是存储限制。 */
      if (!isKnownTimbre(wave)) {
        if (wave) warn.push("音色 " + wave + " 不在音色库里，改用 triangle");
        wave = "triangle";
      } else if (tier && !(TIMBRE_TIERS[tier] || []).includes(wave)) {
        warn.push("音色 " + wave + " 属于「" + TIMBRE_TIER_LABELS[timbreTierOf(wave)] + "」，超出本次所选档位，仍按原音色发声");
      }
      const track = {
        name: typeof rt.name === "string" && rt.name.trim() ? rt.name.trim().slice(0, 16) : "track",
        wave,
        gain: clamp(numOr(rt.gain, 0.18), 0.01, 0.6),
        notes: [],
      };
      const rawNotes = Array.isArray(rt.notes) ? rt.notes : [];
      let capped = false;
      for (const rn of rawNotes) {
        let pitch, start, dur, vel;
        if (Array.isArray(rn)) { pitch = rn[0]; start = rn[1]; dur = rn[2]; vel = rn[3]; }
        else if (rn && typeof rn === "object") {
          pitch = rn.pitch !== undefined ? rn.pitch : (rn.note !== undefined ? rn.note : rn.midi);
          start = rn.start !== undefined ? rn.start : rn.startBeat;
          dur = rn.dur !== undefined ? rn.dur : (rn.durBeats !== undefined ? rn.durBeats : rn.duration);
          vel = rn.vel !== undefined ? rn.vel : rn.velocity;
        } else continue;
        let midi = pitchToMidi(pitch);
        if (midi === null) continue;
        if (midi < 24 || midi > 100) { midi = clamp(midi, 24, 100); }
        const s = numOr(start, null);
        const d = numOr(dur, null);
        if (s === null || d === null || d <= 0) continue;
        // 先判上限再入谱：原写法是「先 push 再判」，于是每首被截断的曲子都会多出 1 个音符
        if (total >= MAX_NOTES) { capped = true; break; }
        track.notes.push({
          midi,
          start: clamp(s, 0, score.bars * bpb),
          dur: clamp(d, 0.05, 16),
          vel: clamp(numOr(vel, 0.75), 0.05, 1),
        });
        total++;
      }
      track.notes.sort((a, b) => a.start - b.start);
      if (track.notes.length) score.tracks.push(track);
      if (capped) { warn.push("音符达到 " + MAX_NOTES + " 上限，已截断（可用「修订」补写后段）"); break; }
    }
    for (const rp of (Array.isArray(raw.percussion) ? raw.percussion : []).slice(0, MAX_PERC)) {
      let kind, beat, vel;
      if (Array.isArray(rp)) { kind = rp[0]; beat = rp[1]; vel = rp[2]; }
      else if (rp && typeof rp === "object") { kind = rp.kind || rp.type; beat = rp.beat !== undefined ? rp.beat : rp.start; vel = rp.vel !== undefined ? rp.vel : rp.velocity; }
      else continue;
      kind = typeof kind === "string" ? kind.toLowerCase().trim() : "";
      if (!PERC_KINDS.includes(kind)) continue;
      const b = numOr(beat, null);
      if (b === null) continue;
      score.percussion.push({ kind, beat: clamp(b, 0, score.bars * bpb), vel: clamp(numOr(vel, 0.7), 0.05, 1) });
    }
    score.percussion.sort((a, b) => a.beat - b.beat);
    // 若音符越界，扩展小节数把内容装回来。
    // 但要留一拍容差：末尾的延长音几乎总会探出小节线一点点（一个和弦的余韵），
    // 那不是新的一小节。不留容差的话，24 小节的曲子会因为 0.2 拍就被撑成 25 小节、
    // 时长从 60 秒变成 62.5 秒——长篇的「时长精确」就废了。
    let maxBeat = score.bars * bpb;
    for (const t of score.tracks) for (const n of t.notes) maxBeat = Math.max(maxBeat, n.start + n.dur);
    for (const p of score.percussion) maxBeat = Math.max(maxBeat, p.beat + 0.5);
    const needed = Math.ceil((maxBeat - TAIL_SLACK_BEATS) / bpb);
    if (needed > score.bars) score.bars = clamp(needed, 1, maxBarsOf(bpb));
    if (!score.tracks.length && !score.percussion.length) warn.push("整顿后没有任何可发声内容");
  } else {
    const rawLayers = Array.isArray(raw.layers) ? raw.layers : (Array.isArray(raw.tracks) ? raw.tracks : []);
    if (!rawLayers.length) warn.push("模型没有给出任何音层");
    for (const rl of rawLayers.slice(0, MAX_LAYERS)) {
      if (!rl || typeof rl !== "object") continue;
      const src = rl.src === "tone" || rl.wave ? "tone" : "noise";
      /* 音效层只认内置波形：scheduleLayer 是直接赋 o.type 的，
         不走谐波谱那条路，所以这里刻意仍用 WAVES 而不是音色库全集。
         档位音色集只作用于旋律音轨。 */
      let wave = typeof rl.wave === "string" ? rl.wave.toLowerCase().trim() : "sine";
      if (!WAVES.includes(wave)) wave = "sine";
      let type = typeof rl.type === "string" ? rl.type.toLowerCase().trim() : (src === "noise" ? "bandpass" : "none");
      if (!FILTER_TYPES.includes(type)) type = src === "noise" ? "bandpass" : "none";
      const layer = {
        src, wave, type,
        f0: clamp(numOr(rl.f0 !== undefined ? rl.f0 : rl.freq, src === "noise" ? 900 : 220), 20, 18000),
        f1: clamp(numOr(rl.f1 !== undefined ? rl.f1 : rl.sweepTo, 0), 0, 18000),
        q: clamp(numOr(rl.q, src === "noise" ? 1.2 : 0.7), 0.1, 24),
        start: clamp(numOr(rl.start, 0), 0, 60),
        dur: clamp(numOr(rl.dur !== undefined ? rl.dur : rl.duration, 1), 0.05, 30),
        attack: clamp(numOr(rl.attack, 0.02), 0.001, 8),
        decay: clamp(numOr(rl.decay, 0.3), 0.01, 12),
        gain: clamp(numOr(rl.gain, 0.4), 0.01, 1),
        pan: clamp(numOr(rl.pan, 0), -1, 1),
      };
      if (layer.f1 <= 0) layer.f1 = layer.f0;
      score.layers.push(layer);
    }
    let end = 1;
    for (const L of score.layers) end = Math.max(end, L.start + L.dur + L.decay);
    score.bars = Math.max(1, Math.min(maxBarsOf(bpb), Math.ceil((end * score.bpm) / (60 * bpb))));
    if (!score.layers.length) warn.push("整顿后没有任何可发声内容");
  }
  applyGroove(score, groove);
  score.groove = GROOVES[groove] ? groove : DEFAULT_GROOVE;   // 记下实际套用的律动，供修订时对账
  return { score, warn };
}

function durationOf(score) {
  if (!score) return 0;
  const beatSec = 60 / score.bpm;
  if (score.mode === "sfx") {
    let end = 0;
    for (const L of score.layers) end = Math.max(end, L.start + L.dur + L.decay);
    return Math.max(0.5, end);
  }
  let maxBeat = score.bars * beatsOf(score);
  for (const t of score.tracks) for (const n of t.notes) maxBeat = Math.max(maxBeat, n.start + n.dur);
  return maxBeat * beatSec;
}

/* ── 基础音源 ─────────────────────────────────────────────────────────── */

/** 确定性白噪声，保证同一乐谱每次渲染逐位一致。 */
function noiseBuffer(ctx) {
  if (ctx.__noiseBuf) return ctx.__noiseBuf;
  const sr = ctx.sampleRate, len = Math.floor(sr * 2);
  const buf = ctx.createBuffer(1, len, sr);
  const d = buf.getChannelData(0);
  let s = 987654321;
  for (let i = 0; i < len; i++) { s = (s * 1103515245 + 12345) & 0x7fffffff; d[i] = s / 0x3fffffff - 1; }
  ctx.__noiseBuf = buf;
  return buf;
}

/** 算法混响脉冲：指数衰减噪声，给声音一个"空间"。 */
function impulseBuffer(ctx, seconds, decay) {
  const sr = ctx.sampleRate, len = Math.floor(sr * seconds);
  const buf = ctx.createBuffer(2, len, sr);
  for (let c = 0; c < 2; c++) {
    const d = buf.getChannelData(c);
    let s = 24681357 + c * 7919;
    for (let i = 0; i < len; i++) {
      s = (s * 1103515245 + 12345) & 0x7fffffff;
      const n = s / 0x3fffffff - 1;
      d[i] = n * Math.pow(1 - i / len, decay);
    }
  }
  return buf;
}

function mkGain(ctx) { return ctx.createGain(); }
function connectPanned(ctx, node, bus, pan) {
  if (pan !== undefined && pan !== null && typeof ctx.createStereoPanner === "function") {
    const p = ctx.createStereoPanner();
    p.pan.value = clamp(pan, -1, 1);
    node.connect(p); p.connect(bus);
  } else node.connect(bus);
}

/** 谐波谱 → PeriodicWave，按谱签名缓存在上下文上（每音都建一张太贵）。 */
function periodicWaveFor(ctx, harm) {
  const key = harm.join(",");
  const cache = ctx.__pwCache || (ctx.__pwCache = new Map());
  const hit = cache.get(key);
  if (hit) return hit;
  const n = harm.length - 1;
  const real = new Float32Array(n + 1);
  const imag = new Float32Array(n + 1);
  // 约定：下标 k 就是第 k 次谐波，0 号是直流（保持 0）
  for (let k = 1; k <= n; k++) imag[k] = harm[k] || 0;
  const pw = ctx.createPeriodicWave(real, imag);   // 默认归一化，避免峰值越界
  cache.set(key, pw);
  return pw;
}

/* ── 低音区专用声源/共振峰（只对低音生效） ──────────────────────────────────────────
   为什么按**音区**分：人声的低通截止本来是 6.5×f0，A2(110Hz) 上只有 715Hz，
   把「啊」的共振峰区（F1≈730 / F2≈1090）整段砍掉 → 低音区只剩嗡嗡声；
   但高音区**绝不能动** —— 把 2.5kHz 以上的能量抬起来（哪怕只到 0.4%）听感就从「人声」
   变成「又亮又刺的电子音」，这条音的高音区必须逐位保持原样。

   lowWeightOf：f0 ≥ lo.hi → 0（高音区，**逐位回落到原表、不建任何共振峰**）；
                f0 ≤ lo.lo → 1（低音区全量）；中间线性过渡，跨音区不会有音色跳变。 */
function lowWeightOf(spec, freq) {
  const L = spec.low;
  if (!L) return 0;
  return clamp((L.hi - freq) / (L.hi - L.lo), 0, 1);
}
/* ── 音区自适应（低/中/高三个音区）的权重与缩放曲线 ─────────────────────────
   机制形状与出处见 docs/timbre-research.md §4。三条硬约束：
     · 锚点必须是 A3：f0 = 220 → cutoff 恒等于 220×fcut；low.hi ≤ 220、high.lo ≥ 220；
     · **A3（中音区）上一切新机制都退化成空操作**（权重恰好 0、缩放系数恰好 1），
       于是"中音区逐位不变"是结构上成立的，而不是靠数值凑出来的；
     · 只用滤波器/增益与数组算术，**音源增量为 0**。
   音区边界是**硬切 + 两侧参数连续**，不做交叉淡化（SF2 规范本身没有交叉淡化生成器，
   我们 2 音源的预算也只够一条边界）。 */

/** 高音区权重（lowWeightOf 的镜像）：f0 ≤ lo → 0（A3 及以下，**逐位回落到原表**）；
    f0 ≥ hi → 1（高音区全量）；中间线性过渡。约束 lo ≥ 220 保证 A3 上恒为 0。 */
function highWeightOf(spec, freq) {
  const H = spec.high;
  if (!H) return 0;
  const lo = H.lo === undefined ? 220 : H.lo;
  const hi = H.hi === undefined ? lo : H.hi;
  if (!(hi > lo)) return freq >= lo ? 1 : 0;
  return clamp((freq - lo) / (hi - lo), 0, 1);
}

/** 体共鸣（body）的音区权重：**低音大、高音小** —— "低音厚、高音瘦"的主力就是它乘在
    固定 Hz 共振峰的增益上。A2(110Hz) → 1.0（实测模态值全量）；A2 以下按 1.0 保持
    （真乐器的体共鸣在最低音区最强）；A3(220Hz) 及以上 → 0（**一个节点都不建**）。 */
function bodyWeightOf(freq) { return clamp((220 - freq) / 110, 0, 1); }

/** 音区衰减缩放（阻尼谐振器 1/f² 规律）：T60(note) = T60_ref · 2^(−2·(note−ref)/12)。
    ref 取 A2(45) —— body 的主力音区，表里的 Q 实测值就在那里，所以 A2 上系数恰好 1.0。
    用在 body 的 q 上：越低的音衰减越长（低音更"厚"、更有余韵），越高的音 Q 越小。 */
function t60ScaleOfNote(midi) { return Math.pow(2, (-2 * (midi - 45)) / 12); }

/** 亮度倾斜（调研文档 §2）：C4 以上 +0.06 dB/八度、C4 以下 −0.15 dB/八度。
    **以 A3 为 0 dB**（两条同式相减，f0 = 220 时恰好 0 → 系数恰好 1.0）→ A3 逐位不变。
    乘在主低通截止上：高音区略提亮、低音区略压暗。 */
function brightnessTiltDb(freq) {
  const C4 = 261.6255653005986;
  const raw = (f) => (f >= C4 ? 0.06 * Math.log2(f / C4) : -0.15 * Math.log2(C4 / f));
  return raw(freq) - raw(220);
}
/** dB → 线性幅度系数（A3 处恰好 1.0） */
function tiltFactor(freq) { return Math.pow(10, brightnessTiltDb(freq) / 20); }

/** 气声层增益 / 气声 LPF 截止的**键缩放曲线（2 折点）** —— Yamaha VL1 的官方做法：
    "用两个折点把不同的截止偏移量应用到键盘不同位置"。折点 (A1,×1.6) (A3,×1.0) (A5,×0.55)：
    低音区气声更多、高音区更少（真乐器高音区的气流噪声占比本来就下降）。
    **A3 处恰好返回 1.0** → 现有音色的中音区逐位不变；折点外按端点斜率线性外推。 */
const BREATH_KEYSCALE = [[33, 1.6], [57, 1.0], [81, 0.55]];
function breathKeyScale(midi) {
  const K = BREATH_KEYSCALE, lo = 0.25, hi = 2.5;
  const at = (i) => K[i][1] + ((K[i + 1][1] - K[i][1]) / (K[i + 1][0] - K[i][0])) * (midi - K[i][0]);
  for (let i = 0; i < K.length; i++) {
    if (midi === K[i][0]) return K[i][1];                       // 折点上恰好命中（A3 = 1.0）
    if (i + 1 < K.length && midi < K[i + 1][0]) return clamp(at(i), lo, hi);
  }
  return clamp(at(K.length - 2), lo, hi);
}

/** 按权重混合三张谐波表：中音区（= harm）、低音区（= low.harm，更长，才够撑 700~1100Hz）、
    高音区（= high.harm）。两个权重都为 0 时**原样返回 harm**，连 PeriodicWave 的归一化
    都不受影响（逐位不变）。音区不重叠（low.hi ≤ 220 ≤ high.lo）→ 权重和 ≤ 1。 */
function harmForPitch(spec, freq, lowW, highW) {
  if (!(lowW > 0) && !(highW > 0)) return spec.harm;
  const a = spec.harm || [];
  const b = (spec.low && spec.low.harm) || [];
  const c = (spec.high && spec.high.harm) || [];
  const n = Math.max(a.length, b.length, c.length);
  const out = new Array(n).fill(0);
  for (let k = 0; k < n; k++) {
    out[k] = (a[k] || 0) * (1 - lowW - highW) + (b[k] || 0) * lowW + (c[k] || 0) * highW;
  }
  return out;
}

/* ── 颤音与微抖动（参数曲线自动化，**零新增音源**） ──────────────────────
   真人的音高不是一条直线：颤音是基频 5~7Hz、±1 个半音上下的周期起伏，再叠一点周期抖动
   （jitter，音高）与振幅抖动（shimmer）。这里用**参数自动化**做 —— 给 AudioParam 下一条
   算出来的 Float32Array 曲线，而不是加 LFO 振荡器，所以**音源节点数一个都不多**
   （人声仍是 主振荡器 + 失谐层 = 2 个），定时导出的耗时也不变。

   三条硬约束（都踩过）：
     · 同一参数、同一时段既 setValueAtTime 又 setValueCurveAtTime 会冲突 —— 浏览器的
       setValueCurveAtTime 对「区间开区间内还有别的自动化事件」直接抛 NotSupportedError。
       做法：detune 整段只用曲线，把失谐层的静态音分当**直流分量**写进曲线；
       gain 的 shimmer 曲线只铺在延音段**内部**（两端各让开 20ms），开区间内没有别的自动化
       事件 —— 这条在真浏览器（Chromium）里实测不抛。
     · 曲线长度按音符**实际发声时长**算（最长 16 拍 = 10 秒），不写死短数组。
     · 抖动必须来自固定种子 PRNG —— 全程不许 Math.random()，否则「两次渲染逐位一致」会挂。 */

/** mulberry32：固定种子 PRNG（确定性、与调用顺序无关）。 */
function mulberry32(seed) {
  let a = seed >>> 0;
  return function () {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** 曲线采样率：5~7Hz 的颤音用 200 点/秒 已经很滑（点与点之间线性插值），
    10 秒长音也只有 2001 个 float（8KB）—— 比按采样率铺小两个数量级。 */
const VIB_CURVE_HZ = 200;
/** 固定种子白噪声表（确定性；表内偏移按声部错开，音符之间不相关）。 */
const VIB_NOISE = (function () {
  const r = mulberry32(20240101), a = new Float32Array(8192);
  for (let i = 0; i < a.length; i++) a[i] = r() * 2 - 1;
  return a;
})();
const smoothWin = (x) => (x <= 0 ? 0 : x >= 1 ? 1 : x * x * (3 - 2 * x));
/* 均匀白噪声 σ=1/√3；3 点滑动平均后 σ=1/(3√3)；τ 秒 EMA 后 σ=σ_白·√(a/(2-a))。 */
const SIG_WHITE = 1 / Math.sqrt(3);
const SIG_MA3 = SIG_WHITE / Math.sqrt(3);

/**
 * 颤音 + 微抖动曲线（单位：音分）。
 * @param {number} spanSec 曲线覆盖的实际发声时长（起音 → 振荡器停）
 * @param {number} noteSec 音符的乐谱时长（用来决定短音要不要颤）
 * @param {object} v       音色里的 vib 参数
 * @param {number} dc      直流分量 = 失谐层的静态音分（主层 0）；整段只用曲线，故写进来
 * @param {number} voice   声部序号（合唱各人的速率/相位不同步）
 * @returns {Float32Array|null} null = 这个音不做颤音（极短音）
 */
function vibratoCurve(spanSec, noteSec, v, dc, voice) {
  /* 短音符不该打颤（0.2s 的十六分音符上颤音很滑稽）：<0.22s 完全不做，
     0.22~0.82s 线性缩幅度，够长的音才给全量。 */
  const durScale = clamp((noteSec - 0.22) / 0.6, 0, 1);
  if (durScale <= 0.001 || !(spanSec > 0)) return null;
  const n = Math.max(2, Math.round(spanSec * VIB_CURVE_HZ) + 1);
  const dt = spanSec / (n - 1);
  const out = new Float32Array(n);
  const w = v.voices[voice % v.voices.length];
  /* 起振头不抖（真人也是唱稳了才出颤音），收尾淡出到静态值（尾部不会停在一个音分上）。 */
  const fadeIn = Math.min(0.18, spanSec * 0.3);
  const fadeOut = Math.min(0.45, spanSec * 0.3);
  const off = (v.noiseOff + 4099 * voice) & 8191;
  const aEma = 1 - Math.exp(-dt / 0.35);
  const kMid = v.jitter / SIG_MA3;
  const kSlow = v.drift / (SIG_WHITE * Math.sqrt(aEma / (2 - aEma)));
  const w1 = 2 * Math.PI * w.rate, w2 = 2 * Math.PI * (v.wobbleRate || 0);
  let ema = 0;
  for (let i = 0; i < n; i++) {
    const t = i * dt;
    const x = VIB_NOISE[(off + i) & 8191];
    ema += aEma * (x - ema);
    const mid = (VIB_NOISE[(off + i - 1) & 8191] + x + VIB_NOISE[(off + i + 1) & 8191]) / 3;
    /* 颤音深度本身也有慢起伏（±wobble）—— 否则听起来像节拍器打的波浪。 */
    const depth = 1 + v.wobble * Math.sin(w2 * t + w.phase * 0.5);
    const pitch = depth * w.cents * Math.sin(w1 * t + w.phase) + kMid * mid + kSlow * ema;
    let win = smoothWin(t / fadeIn);
    const left = spanSec - t;
    if (left < fadeOut) win = Math.min(win, smoothWin(left / fadeOut));
    out[i] = dc + win * durScale * pitch;
  }
  out[n - 1] = dc;
  return out;
}

/**
 * 振幅抖动（shimmer）曲线：铺在延音段 (t0+A+D, holdEnd)，首尾都正好等于稳态增益
 * （不会咔一下）。区间开区间内没有任何别的自动化事件 —— 浏览器不会抛 NotSupportedError。
 */
function shimmerCurve(spanSec, lvl, sh) {
  if (!sh || !(spanSec > 0.3)) return null;
  const n = Math.max(2, Math.round(spanSec * VIB_CURVE_HZ) + 1);
  const dt = spanSec / (n - 1);
  const out = new Float32Array(n);
  const off = sh.noiseOff & 8191;
  const aEma = 1 - Math.exp(-dt / 0.5);
  const kMid = sh.mid / SIG_MA3;
  const kSlow = sh.slow / (SIG_WHITE * Math.sqrt(aEma / (2 - aEma)));
  let ema = 0;
  for (let i = 0; i < n; i++) {
    const t = i * dt;
    const x = VIB_NOISE[(off + i) & 8191];
    ema += aEma * (x - ema);
    const mid = (VIB_NOISE[(off + i - 1) & 8191] + x + VIB_NOISE[(off + i + 1) & 8191]) / 3;
    const ramp = Math.min(1, t / 0.08, (spanSec - t) / 0.08);   // 首尾 80ms 收口，与前后包络无缝
    out[i] = lvl * (1 + ramp * (kMid * mid + kSlow * ema));
  }
  return out;
}

/** 一个有音高的音：振荡器 + 低通 + ADSR。返回它最后停止的时刻。 */
function scheduleNote(ctx, bus, midi, t0, dur, vel, wave, gain, pan, nodes) {
  const spec = TIMBRES[wave];

  /* 基础档（以及任何未知名字）走这一支 —— **代码与加音色库之前逐字一致**，
     这是"基础音色集 = 与旧版完全等价"的保证，改动前采的渲染校验和就靠它守住。 */
  if (!spec || spec.plain) {
    const w = WAVES.includes(wave) ? wave : "triangle";
    const freq = midiToFreq(midi);
    const osc = ctx.createOscillator();
    osc.type = w;
    osc.frequency.setValueAtTime(freq, t0);

    const filt = ctx.createBiquadFilter();
    filt.type = "lowpass";
    filt.frequency.setValueAtTime(clamp(freq * 7, 320, 15000), t0);
    filt.Q.value = 0.7;

    const g = mkGain(ctx);
    const peak = clamp(vel, 0, 1) * gain;
    const A = Math.min(0.014, dur * 0.25) + 0.002;
    const D = Math.min(0.17, dur * 0.5) + 0.003;
    const sus = 0.66;
    const R = Math.min(0.5, Math.max(0.07, dur * 0.4));
    const holdEnd = Math.max(t0 + A + D, t0 + dur - 0.01);
    g.gain.setValueAtTime(0.0001, t0);
    g.gain.exponentialRampToValueAtTime(Math.max(0.0002, peak), t0 + A);
    g.gain.exponentialRampToValueAtTime(Math.max(0.0002, peak * sus), t0 + A + D);
    g.gain.setValueAtTime(Math.max(0.0002, peak * sus), holdEnd);
    g.gain.exponentialRampToValueAtTime(0.0001, holdEnd + R);

    osc.connect(filt); filt.connect(g);
    connectPanned(ctx, g, bus, pan);
    osc.start(t0); osc.stop(holdEnd + R + 0.03);
    nodes.push(osc);
    return holdEnd + R + 0.03;
  }

  /* ── 扩展路径：音色库里的具名音色 ───────────────────────────────── */
  const freq = midiToFreq(midi);
  const peak = clamp(vel, 0, 1) * gain * (spec.trim === undefined ? 1 : spec.trim);

  /* 包络：给了 amp 就按音色走（拨弦的短促、铺垫的慢起都靠它），
     不给则沿用"随 dur 推导"，与基础档同源。 */
  let A, D, sus, R;
  if (spec.amp) {
    A = clamp(spec.amp[0], 0.001, Math.max(0.02, dur));
    D = clamp(spec.amp[1], 0.001, Math.max(0.02, dur));
    sus = clamp(spec.amp[2], 0, 1);
    R = clamp(spec.amp[3], 0.005, 4);
  } else {
    A = Math.min(0.014, dur * 0.25) + 0.002;
    D = Math.min(0.17, dur * 0.5) + 0.003;
    sus = 0.66;
    R = Math.min(0.5, Math.max(0.07, dur * 0.4));
  }
  const sLvl = Math.max(0.0002, peak * sus);
  const holdEnd = Math.max(t0 + A + D, t0 + dur - 0.01);
  /* 振荡器的停时刻先算出来 —— 颤音曲线要按**实际发声时长**铺满整条音（含 release
     尾巴），尾部淡出到静态失谐量，不会在尾巴上停住一个偏移。表达式与原来逐字相同。 */
  const stopAt = (sus > 0.001 ? holdEnd : t0 + A + D) + R + 0.03;
  const vib = spec.vib || null;          // 只有带 vib 字段的音色（当前是 choir）走曲线
  const g = mkGain(ctx);
  g.gain.setValueAtTime(0.0001, t0);
  g.gain.exponentialRampToValueAtTime(Math.max(0.0002, peak), t0 + A);
  g.gain.exponentialRampToValueAtTime(sLvl, t0 + A + D);
  /* 振幅抖动（shimmer）：延音段用一条曲线替代原来那句平直的 setValueAtTime(sLvl, holdEnd)。
     曲线铺在 (t0+A+D, holdEnd) 的**内部**（两端各让开 20ms，避边）；区间开区间内没有任何
     别的自动化事件，所以浏览器不会对 setValueCurveAtTime 抛 NotSupportedError；
     曲线首尾值都正好是 sLvl，衔接无缝。 */
  const shimSpan = holdEnd - (t0 + A + D) - 0.04;
  const shimC = vib ? shimmerCurve(shimSpan, sLvl, vib.shimmer) : null;
  if (shimC) g.gain.setValueCurveAtTime(shimC, t0 + A + D + 0.02, shimSpan);
  else if (holdEnd > t0 + A + D) g.gain.setValueAtTime(sLvl, holdEnd);
  g.gain.exponentialRampToValueAtTime(0.0001, holdEnd + R);

  /* 低通：截止倍数与 Q 由音色给；fenv 让截止扫一遍 —— 拨弦的"亮起振→暗余音"
     就是这么来的，**不新增任何节点**。 */
  const filt = ctx.createBiquadFilter();
  filt.type = "lowpass";
  filt.Q.value = spec.fq === undefined ? 0.7 : spec.fq;
  /* cutFloor：截止的**绝对 Hz 下限**，只对低音生效 —— 人不许提亮，但元音区必须露出来。
     截止本来 = freq × fcut；人声的 6.5×f0 在 A2(110Hz) 上只有 715Hz，把「啊」的共振峰区
     （F1 730 / F2 1090）整段砍掉，低音区只剩嗡嗡声。给一个绝对下限后，低音也能露出元音区；
     而 f0 ≥ 地板/fcut 的音上 6.5×f0 本来就高于地板 → 截止值一个比特都不变，
     **高音区（≥200Hz）的渲染逐位保持原样**。 */
  /* 部分键盘跟踪（业界 50~70%）：cutoff(f0) = 220 × mult × (f0/220)^kt，**锚在 A3** ——
     f0 = 220 时 Math.pow(220/220, kt) = Math.pow(1, kt) = 1，截止恒等于 220×mult，
     与旧式的 freq×mult 逐位相同；缺省 kt = 1 也走这条式子，所以"与旧版逐位等价"对任何
     省略 keyTrack 的音色都成立。再乘亮度倾斜（A3 处系数恰好 1.0）。
     cutFloor 是既有的绝对 Hz 下限（只对低音生效），cutMax 是新增的绝对 Hz 上限安全阀。 */
  const kt = spec.keyTrack === undefined ? 1 : spec.keyTrack;
  const cutOf = (mult) => {
    const c = clamp(220 * mult * Math.pow(freq / 220, kt), 320, 15000) * tiltFactor(freq);
    return spec.cutFloor ? Math.max(c, spec.cutFloor) : c;
  };
  const cutBase = cutOf(spec.fcut === undefined ? 7 : spec.fcut);
  if (spec.fenv) {
    filt.frequency.setValueAtTime(cutOf(spec.fenv[0]), t0);
    filt.frequency.exponentialRampToValueAtTime(cutOf(spec.fenv[1]), t0 + clamp(spec.fenv[2], 0.01, 4));
  } else {
    filt.frequency.setValueAtTime(cutBase, t0);
  }

  // 主振荡器：有谐波谱就设波（**不能同时赋 type="custom"，会抛 InvalidStateError**），否则用内置波形
  const lowW = lowWeightOf(spec, freq);          // 低音区权重（0 = 中/高音区，一切照旧）
  const highW = highWeightOf(spec, freq);        // 高音区权重（A3 及以下恒为 0）
  const bodyW = bodyWeightOf(freq);              // 体共鸣权重（A3 及以上恒为 0）
  const harmUsed = harmForPitch(spec, freq, lowW, highW);
  const oscs = [];
  const mkOsc = () => {
    const o = ctx.createOscillator();
    if (harmUsed) o.setPeriodicWave(periodicWaveFor(ctx, harmUsed));
    else o.type = spec.type || "triangle";
    o.frequency.setValueAtTime(freq, t0);
    return o;
  };
  /* 颤音/微抖动铺在 detune 上 —— 主振荡器的 detune 原本没人动；失谐层原本是
     setValueAtTime(spec.detune)：同一参数同一时段不能既 setValueAtTime 又
     setValueCurveAtTime，故**整段只用曲线**，把静态失谐量当直流分量写进曲线。
     曲线是算出来的数组 —— **不新增任何音源节点**。 */
  const applyVib = (o, dc, voice) => {
    const c = vib ? vibratoCurve(stopAt - t0, dur, vib, dc, voice) : null;
    if (!c) return false;
    o.detune.setValueCurveAtTime(c, t0, stopAt - t0);
    return true;
  };
  const o1 = mkOsc();
  applyVib(o1, 0, 0);
  oscs.push(o1);
  if (spec.detune) {            // 失谐叠一层：弦乐群感、pad 变厚（每音 +1 个音源）
    const o2 = mkOsc();
    if (!applyVib(o2, spec.detune, 1)) o2.detune.setValueAtTime(spec.detune, t0);
    oscs.push(o2);
  }
  if (spec.fm) {                // FM：钟琴/电钢/金属的非谐分音只能靠调制器（每音 +1 个音源）
    const mod = ctx.createOscillator();
    mod.type = "sine";
    mod.frequency.setValueAtTime(freq * spec.fm.ratio, t0);
    const mg = mkGain(ctx);
    mg.gain.setValueAtTime(freq * spec.fm.index, t0);
    mod.connect(mg);
    for (const o of oscs) mg.connect(o.frequency);
    mod.start(t0); mod.stop(holdEnd + R + 0.03);
    nodes.push(mod);
  }

  for (const o of oscs) o.connect(filt);

  /* 元音共振峰（固定绝对 Hz，不乘 freq）：在低通之后串 peaking biquad。
     **只在低音区启用**（lowW > 0）—— 高音区一加增益就会把谱斜率抬起来 = 提亮 = 甲的死因。
     只做 F1/F2、**不给 2440Hz 的 F3**：能量只落在 700~1100Hz，2.5kHz 以上不动。
     噪声（气声）接在 filt 上，所以呼气同样过这道「声道」。 */
  const fmts = [];
  if (spec.formants) for (const fm of spec.formants) fmts.push({ f: fm.f, q: fm.q, gain: fm.gain === undefined ? 9 : fm.gain });
  /* 体共鸣支路（body）：**固定 Hz**、低 Q 双极点，增益乘音区权重 bodyW（低音大、高音小）。
     这是"低音厚、高音瘦"的主力，且**只花滤波器、不占音源预算**。A3 及以上 bodyW = 0
     → 一个节点都不建（逐位不变）。表里的 q 是 A2 处的实测 Q，更低的音按 T60 规律拉长。 */
  if (spec.body && bodyW > 0) {
    const qScale = t60ScaleOfNote(midi);
    for (const bd of spec.body) {
      const q = clamp((bd.q === undefined ? 4 : bd.q) * qScale, 0.4, 24);
      fmts.push({ f: bd.f, q, gain: clamp((bd.gain === undefined ? 3 : bd.gain) * bodyW, 0, 24) });
    }
  }
  if (spec.low && spec.low.formants && lowW > 0) {
    for (const fm of spec.low.formants) fmts.push({ f: fm.f, q: fm.q, gain: (fm.gain === undefined ? 9 : fm.gain) * lowW });
  }
  /* 高音区逃生舱（high.formants）：只在高音区启用，语义与 low.formants 镜像 ——
     给"高音区反而更鼻音/更亮"的乐器。 */
  if (spec.high && spec.high.formants && highW > 0) {
    for (const fm of spec.high.formants) fmts.push({ f: fm.f, q: fm.q, gain: (fm.gain === undefined ? 9 : fm.gain) * highW });
  }
  let tail = filt;
  if (fmts.length) {
    for (const fm of fmts) {
      const pf = ctx.createBiquadFilter();
      pf.type = "peaking";
      pf.frequency.value = clamp(fm.f, 40, 18000);
      pf.Q.value = clamp(fm.q === undefined ? 4 : fm.q, 0.1, 24);
      pf.gain.value = clamp(fm.gain, -24, 24);
      tail.connect(pf);
      tail = pf;
    }
  }
  tail.connect(g);
  connectPanned(ctx, g, bus, pan);

  // 噪声起振（气声 / 弓擦）：走同一个低通与包络，音色才统一
  if (spec.noise) {
    const ns = ctx.createBufferSource();
    ns.buffer = noiseBuffer(ctx); ns.loop = true;
    const bp = ctx.createBiquadFilter();
    bp.type = "bandpass";
    bp.frequency.value = clamp(spec.noise.band * breathKeyScale(midi), 200, 12000);
    bp.Q.value = 0.9;
    const ng = mkGain(ctx);
    ng.gain.setValueAtTime(0.0002, t0);
    ng.gain.exponentialRampToValueAtTime(Math.max(0.0002, peak * spec.noise.gain * breathKeyScale(midi)), t0 + 0.006);
    ng.gain.exponentialRampToValueAtTime(0.0002, t0 + clamp(spec.noise.decay, 0.01, 2));
    ns.connect(bp); bp.connect(ng); ng.connect(filt);
    ns.start(t0); ns.stop(t0 + clamp(spec.noise.decay, 0.01, 2) + 0.03);
    nodes.push(ns);
  }

  /* 呼吸感：**全程**的低电平气声，而不是只有起音那一下。
     真唱长音时的"气息"是整段都在的（声门闭合不全 → 湍流噪声）；只有起振有气会变成"呼"一下。
     包络分两段：20ms 冲到 onset 倍率（"ha" 的那口气），0.35s 落到持续电平（气息底噪），
     最后跟主体一起收。走长笛那套：噪声 → 带通 → 自己的增益 → **同一个低通 + 同一串共振峰 +
     同一个音符包络 g**，所以气和嗓音是同一条"声道"出来的，音色统一。
     成本：+1 个音源（人声 2 → 3 = 专业档增量上限 2）；BiquadFilter/Gain 不算音源。 */
  if (spec.breath) {
    const ns = ctx.createBufferSource();
    ns.buffer = noiseBuffer(ctx); ns.loop = true;
    const bp = ctx.createBiquadFilter();
    bp.type = "bandpass";
    bp.frequency.value = clamp(spec.breath.band * breathKeyScale(midi), 200, 12000);
    bp.Q.value = clamp(spec.breath.q === undefined ? 0.8 : spec.breath.q, 0.2, 12);
    const ng = mkGain(ctx);
    const bks = breathKeyScale(midi);            // 气声层增益键缩放（A3 处恰好 1.0）
    const lvlSus = Math.max(0.0002, peak * spec.breath.gain * bks);
    const lvlOn = Math.max(lvlSus, peak * spec.breath.gain * bks * (spec.breath.onset === undefined ? 3 : spec.breath.onset));
    ng.gain.setValueAtTime(0.0002, t0);
    ng.gain.exponentialRampToValueAtTime(lvlOn, t0 + 0.02);
    ng.gain.exponentialRampToValueAtTime(lvlSus, t0 + 0.35);
    ng.gain.setValueAtTime(lvlSus, Math.max(t0 + 0.36, holdEnd));
    ng.gain.exponentialRampToValueAtTime(0.0002, holdEnd + R);
    ns.connect(bp); bp.connect(ng); ng.connect(filt);
    ns.start(t0); ns.stop(holdEnd + R + 0.03);
    nodes.push(ns);
  }

  /* 收尾时刻：sus=0 的音色（拨弦/钟琴）衰减完就没声了，不必让振荡器陪站到 dur 末，
     早停能省下不少节点存活时间。声音不受影响。（stopAt 已在上文算好，供颤音曲线用） */
  for (const o of oscs) { o.start(t0); o.stop(stopAt); nodes.push(o); }
  return stopAt;
}

/** 打击乐：全部用振荡器与噪声合成，无需采样。返回它最后停止的时刻。 */
function schedulePerc(ctx, bus, kind, t0, vel, nodes) {
  const v = clamp(vel, 0, 1);
  if (kind === "kick") {
    const o = ctx.createOscillator(); o.type = "sine";
    o.frequency.setValueAtTime(148, t0);
    o.frequency.exponentialRampToValueAtTime(44, t0 + 0.13);
    const g = mkGain(ctx);
    g.gain.setValueAtTime(0.0001, t0);
    g.gain.exponentialRampToValueAtTime(0.95 * v, t0 + 0.005);
    g.gain.exponentialRampToValueAtTime(0.0001, t0 + 0.42);
    o.connect(g); g.connect(bus); o.start(t0); o.stop(t0 + 0.46); nodes.push(o);
    return t0 + 0.46;
  }
  if (kind === "snare") {
    const n = ctx.createBufferSource(); n.buffer = noiseBuffer(ctx); n.loop = true;
    const bp = ctx.createBiquadFilter(); bp.type = "bandpass"; bp.frequency.value = 1750; bp.Q.value = 0.85;
    const g = mkGain(ctx);
    g.gain.setValueAtTime(0.0001, t0);
    g.gain.exponentialRampToValueAtTime(0.5 * v, t0 + 0.004);
    g.gain.exponentialRampToValueAtTime(0.0001, t0 + 0.2);
    n.connect(bp); bp.connect(g); g.connect(bus); n.start(t0); n.stop(t0 + 0.24); nodes.push(n);
    const o = ctx.createOscillator(); o.type = "triangle"; o.frequency.setValueAtTime(196, t0);
    const g2 = mkGain(ctx);
    g2.gain.setValueAtTime(0.0001, t0);
    g2.gain.exponentialRampToValueAtTime(0.22 * v, t0 + 0.004);
    g2.gain.exponentialRampToValueAtTime(0.0001, t0 + 0.12);
    o.connect(g2); g2.connect(bus); o.start(t0); o.stop(t0 + 0.15); nodes.push(o);
    return t0 + 0.24;
  }
  if (kind === "hat") {
    const n = ctx.createBufferSource(); n.buffer = noiseBuffer(ctx); n.loop = true;
    const hp = ctx.createBiquadFilter(); hp.type = "highpass"; hp.frequency.value = 7400;
    const g = mkGain(ctx);
    const dec = 0.035 + 0.075 * v;
    g.gain.setValueAtTime(0.0001, t0);
    g.gain.exponentialRampToValueAtTime(0.24 * v, t0 + 0.002);
    g.gain.exponentialRampToValueAtTime(0.0001, t0 + dec);
    n.connect(hp); hp.connect(g); g.connect(bus); n.start(t0); n.stop(t0 + dec + 0.03); nodes.push(n);
    return t0 + dec + 0.03;
  }
  if (kind === "clap") {
    for (let i = 0; i < 3; i++) {
      const t = t0 + i * 0.011;
      const n = ctx.createBufferSource(); n.buffer = noiseBuffer(ctx); n.loop = true;
      const bp = ctx.createBiquadFilter(); bp.type = "bandpass"; bp.frequency.value = 1150; bp.Q.value = 1.3;
      const g = mkGain(ctx);
      g.gain.setValueAtTime(0.0001, t);
      g.gain.exponentialRampToValueAtTime(0.34 * v, t + 0.002);
      g.gain.exponentialRampToValueAtTime(0.0001, t + 0.028);
      n.connect(bp); bp.connect(g); g.connect(bus); n.start(t); n.stop(t + 0.05); nodes.push(n);
    }
    const n = ctx.createBufferSource(); n.buffer = noiseBuffer(ctx); n.loop = true;
    const bp = ctx.createBiquadFilter(); bp.type = "bandpass"; bp.frequency.value = 1050; bp.Q.value = 1.1;
    const g = mkGain(ctx);
    g.gain.setValueAtTime(0.0001, t0 + 0.033);
    g.gain.exponentialRampToValueAtTime(0.16 * v, t0 + 0.036);
    g.gain.exponentialRampToValueAtTime(0.0001, t0 + 0.16);
    n.connect(bp); bp.connect(g); g.connect(bus); n.start(t0 + 0.033); n.stop(t0 + 0.2); nodes.push(n);
    return t0 + 0.2;
  }
  if (kind === "tom") {
    const o = ctx.createOscillator(); o.type = "sine";
    o.frequency.setValueAtTime(268, t0);
    o.frequency.exponentialRampToValueAtTime(92, t0 + 0.19);
    const g = mkGain(ctx);
    g.gain.setValueAtTime(0.0001, t0);
    g.gain.exponentialRampToValueAtTime(0.6 * v, t0 + 0.006);
    g.gain.exponentialRampToValueAtTime(0.0001, t0 + 0.34);
    o.connect(g); g.connect(bus); o.start(t0); o.stop(t0 + 0.38); nodes.push(o);
    return t0 + 0.38;
  }
}

/** 音效层：噪声或单音，带滤波扫频与包络。返回它最后停止的时刻。 */
function scheduleLayer(ctx, bus, L, t0, nodes) {
  const start = t0 + L.start;
  const dur = L.dur;
  const A = Math.min(L.attack, dur * 0.9);
  const relStart = Math.max(start + A + 0.001, start + dur);
  const end = relStart + L.decay;
  const g = mkGain(ctx);
  const peak = L.gain * 0.55;
  g.gain.setValueAtTime(0.0001, start);
  g.gain.linearRampToValueAtTime(peak, start + A);
  if (relStart > start + A) g.gain.setValueAtTime(peak, relStart);
  g.gain.exponentialRampToValueAtTime(0.0001, end);

  const filt = ctx.createBiquadFilter();
  filt.type = L.type === "none" ? "allpass" : L.type;
  filt.Q.value = L.q;
  const f0 = clamp(L.f0, 20, 18000);
  const f1 = clamp(L.f1, 20, 18000);
  filt.frequency.setValueAtTime(f0, start);
  if (Math.abs(f1 - f0) > 1) filt.frequency.exponentialRampToValueAtTime(f1, relStart);

  if (L.src === "noise") {
    const n = ctx.createBufferSource();
    n.buffer = noiseBuffer(ctx); n.loop = true;
    n.connect(filt); filt.connect(g);
    n.start(start); n.stop(end + 0.04);
    nodes.push(n);
  } else {
    const o = ctx.createOscillator();
    o.type = L.wave;
    o.frequency.setValueAtTime(f0, start);
    if (Math.abs(f1 - f0) > 1) o.frequency.exponentialRampToValueAtTime(f1, relStart);
    o.connect(filt); filt.connect(g);
    o.start(start); o.stop(end + 0.04);
    nodes.push(o);
  }
  connectPanned(ctx, g, bus, L.pan);
  return end + 0.04;
}

/**
 * 三次软削波曲线，作为最后一道防线。
 *
 * 为什么必须有：DynamicsCompressor 是压缩器，不是砖墙限幅器。实测把振幅
 * 2.0 的信号送进去，出来是 1.32——它降低了响度，却完全不保证输出不超过
 * 满刻度。真正保证"永不削顶"只能靠一个把输出域钳死的有界函数。
 *
 * 形状 tanh(drive·x)/drive：原点斜率恰为 1（小信号原样通过，不损失透明度），
 * 上界为 tanh(drive)/drive。drive=0.6 时上界 ≈0.895，即 -0.96 dBFS，
 * 留出了余量给 16-bit 量化。
 */
function softClipCurve(n, drive) {
  const c = new Float32Array(n);
  for (let i = 0; i < n; i++) {
    const x = (i / (n - 1)) * 2 - 1;
    c[i] = Math.tanh(drive * x) / drive;
  }
  return c;
}

/**
 * 建总线链：一次播放只建**一套**（干/湿 + 混响 + 压缩 + 软削波）。
 *
 * 为什么单独拆出来：实时播放改成滚动排程后，每个窗口都往同一条总线上挂音符。
 * 混响与削波只能有一份 —— 每个窗口各建一个卷积器不只是白烧 CPU，混响尾巴
 * 还会在窗口边界被硬切。
 * opts.analyser —— 可选的 AnalyserNode，串在主链上
 * opts.volume   —— 用户音量（总线余量在这里统一乘 HEADROOM）
 * 返回 { master, limiter, shaper }
 */
function buildBus(ctx, dest, o, score) {
  const busOut = mkGain(ctx);
  // 留出余量，让软削波只当安全网，而不是常态工作点。
  busOut.gain.value = (o.volume === undefined ? 1 : o.volume) * HEADROOM;

  const dry = mkGain(ctx);
  const wet = mkGain(ctx);
  const rev = score.fx ? score.fx.reverb : 0.3;
  wet.gain.value = clamp(rev, 0, 0.9);
  dry.gain.value = 1 - clamp(rev, 0, 0.9) * 0.4;

  busOut.connect(dry);
  if (wet.gain.value > 0.002 && typeof ctx.createConvolver === "function") {
    const conv = ctx.createConvolver();
    conv.buffer = impulseBuffer(ctx, score.mode === "sfx" ? 3.4 : 2.2, score.mode === "sfx" ? 2.2 : 2.7);
    busOut.connect(conv); conv.connect(wet);
  }

  // 压缩器只做"胶水"，让整体更贴合；真正的防削顶交给后面的软削波。
  const limiter = ctx.createDynamicsCompressor();
  limiter.threshold.value = -10;
  limiter.knee.value = 10;
  limiter.ratio.value = 3;
  limiter.attack.value = 0.008;
  limiter.release.value = 0.25;

  // 安全网：无论前面送进来多响的信号，输出都被钳在 ±tanh(drive)/drive 之内。
  let shaper = null;
  if (typeof ctx.createWaveShaper === "function") {
    shaper = ctx.createWaveShaper();
    shaper.curve = softClipCurve(4096, 0.6);
  }

  // 主链：总线 → (干声 + 湿声) → [分析器] → 压缩器 → [软削波] → 输出
  if (o.analyser) { dry.connect(o.analyser); wet.connect(o.analyser); o.analyser.connect(limiter); }
  else { dry.connect(limiter); wet.connect(limiter); }
  if (shaper) { limiter.connect(shaper); shaper.connect(dest); }
  else limiter.connect(dest);

  return { master: busOut, limiter, shaper };
}

/**
 * 把 [fromBeat, toBeat) 这一段音乐排进 t0 对应的时刻。
 *
 * 为什么要 toBeat：实时播放走「滚动排程」——只把未来几十秒建成音频图，图的规模
 * 从此只跟**密度**有关、跟曲长无关（原因见 SCHED_WINDOW 处的说明）。离线导出仍走
 * buildGraph，一次排满全曲，行为不变。
 *
 * opts.midNote —— 默认 true：跨过起点的长音从起点切一半接着响（中途起播／跳时间要用）。
 *                 滚动排程的后续窗口传 false，否则同一颗音会被排第二遍。
 * 返回这批音里「最后一个还在响的时刻」，供调用方决定何时可以断开这批节点。
 */
function scheduleRange(ctx, bus, score, opts) {
  const o = opts || {};
  const t0 = o.t0 === undefined ? 0 : o.t0;
  const fromBeat = o.fromBeat || 0;
  const toBeat = o.toBeat === undefined ? Infinity : o.toBeat;
  const midNote = o.midNote !== false;
  const nodes = o.nodes || [];
  const beatSec = 60 / score.bpm;
  let end = t0;
  const later = (t) => { if (t > end) end = t; };

  const tOf = (beat) => t0 + (beat - fromBeat) * beatSec;

  if (score.mode === "melody") {
    for (const track of score.tracks) {
      for (const n of track.notes) {
        if (n.start >= toBeat) continue;             // 还没到：留给后面的窗口
        const nEnd = n.start + n.dur;
        if (nEnd <= fromBeat) continue;
        let s = n.start, d = n.dur;
        if (s < fromBeat) {
          if (!midNote) continue;                    // 窗口边界：上一批已经排过它
          d = nEnd - fromBeat; s = fromBeat;
        }
        if (d <= 0.02) continue;
        later(scheduleNote(ctx, bus, n.midi, tOf(s), d * beatSec, n.vel, track.wave, track.gain, track.pan, nodes));
      }
    }
    for (const p of score.percussion) {
      if (p.beat < fromBeat || p.beat >= toBeat) continue;
      later(schedulePerc(ctx, bus, p.kind, tOf(p.beat), p.vel, nodes));
    }
  } else {
    /* 音效层的时间轴单位是「秒」（见 durationOf 与 scheduleLayer），
       而 fromBeat 是「拍」。原先写 t0 - fromBeat、并拿 fromBeat 直接和 L.start 比，
       是把秒和拍相减/相比；只在 fromBeat=0 时恰好没错，中途起播会整体错位。 */
    const fromSec = fromBeat * beatSec;
    const toSec = toBeat * beatSec;
    for (const L of score.layers) {
      if (L.start >= toSec) continue;                 // 还没到：留给后面的窗口
      if (L.start + L.dur + L.decay <= fromSec) continue;
      if (L.start < fromSec && !midNote) continue;    // 窗口边界：上一批已经排过它
      later(scheduleLayer(ctx, bus, L, t0 - fromSec, nodes));
    }
  }

  return end;
}

/** 一次把全曲建成一张图。离线导出／校验用；实时播放走滚动排程（见 pump）。 */
function buildGraph(ctx, score, dest, opts) {
  const o = opts || {};
  const bus = buildBus(ctx, dest, o, score);
  const nodes = [];
  scheduleRange(ctx, bus.master, score, {
    t0: o.t0 === undefined ? 0 : o.t0,
    fromBeat: o.fromBeat || 0,
    nodes,
  });
  return { master: bus.master, nodes, limiter: bus.limiter, shaper: bus.shaper };
}

/** 离线渲染成 AudioBuffer（供导出与校验）。 */
async function renderOffline(score, opts) {
  const o = opts || {};
  const sr = o.sampleRate || 44100;
  const tail = o.tail === undefined ? 2 : o.tail;
  const total = durationOf(score) + tail;
  // durationOf 只认整顿后的乐谱（音符是 {midi,start,dur,vel} 而非数组）。
  // 传原始乐谱进来会算出 NaN，与其让 OfflineAudioContext 抛一句看不懂的错，
  // 不如在这里把话说清楚。
  if (!isFinite(total) || total <= 0) {
    throw new Error("乐谱时长无效（" + total + "），请先用 normalizeScore 整顿后再渲染");
  }
  const Ctor = o.OfflineCtor
    || (typeof OfflineAudioContext !== "undefined" ? OfflineAudioContext : null)
    || (typeof globalThis !== "undefined" && globalThis.OfflineAudioContext)
    || null;
  if (!Ctor) throw new Error("当前环境不支持 OfflineAudioContext");
  const ctx = new Ctor(2, Math.ceil(total * sr), sr);
  buildGraph(ctx, score, ctx.destination, { t0: 0, fromBeat: 0, volume: 1 });
  return await ctx.startRendering();
}

/** 写 WAV 头。encodeWav 与 encodeWavAsync 共用，避免两份格式定义漂移。 */
function wavHeader(dv, ch, len, sr) {
  const dataBytes = len * ch * 2;
  const ws = (off, str) => { for (let i = 0; i < str.length; i++) dv.setUint8(off + i, str.charCodeAt(i)); };
  ws(0, "RIFF"); dv.setUint32(4, 36 + dataBytes, true); ws(8, "WAVE");
  ws(12, "fmt "); dv.setUint32(16, 16, true); dv.setUint16(20, 1, true);
  dv.setUint16(22, ch, true); dv.setUint32(24, sr, true);
  dv.setUint32(28, sr * ch * 2, true); dv.setUint16(32, ch * 2, true); dv.setUint16(34, 16, true);
  ws(36, "data"); dv.setUint32(40, dataBytes, true);
  return dataBytes;
}

/** 把 [from, to) 帧写进 dv；off 是起始字节偏移。抽出来给分片版复用。 */
function wavWriteFrames(dv, chans, from, to, off) {
  const ch = chans.length;
  for (let i = from; i < to; i++) {
    for (let c = 0; c < ch; c++) {
      let s = chans[c][i];
      if (s > 1) s = 1; else if (s < -1) s = -1;
      dv.setInt16(off, s < 0 ? s * 0x8000 : s * 0x7fff, true);
      off += 2;
    }
  }
  return off;
}

/** AudioBuffer → 16-bit PCM WAV（同步版）。离线校验用这个。 */
function encodeWav(buffer) {
  const ch = buffer.numberOfChannels;
  const len = buffer.length;
  const ab = new ArrayBuffer(44 + len * ch * 2);
  const dv = new DataView(ab);
  wavHeader(dv, ch, len, buffer.sampleRate);
  const chans = [];
  for (let c = 0; c < ch; c++) chans.push(buffer.getChannelData(c));
  wavWriteFrames(dv, chans, 0, len, 44);
  return new Uint8Array(ab);
}

/**
 * 同上，但**分片 + 让出主线程**。
 *
 * 为什么必须分片：一首 5 分钟的曲子是 13.3M 帧 × 2 声道 = 2660 万次写入。
 * 一次性同步写完，主线程要卡住很久——实测在可见标签页里导出 5 分钟曲目时，
 * 界面整个冻住：进度不动、播放头不走，老板会以为程序死了（"点了下载后就没音了"）。
 * 分片成每片 ~40 万帧、片间 await 一次，主线程就能喘气：按钮上的百分比会走，
 * 播放头继续推进，正在播放的音频也不会被拖死。
 */
function encodeWavAsync(buffer, onProgress) {
  const CHUNK = 400000;
  const ch = buffer.numberOfChannels;
  const len = buffer.length;
  const sr = buffer.sampleRate;
  const ab = new ArrayBuffer(44 + len * ch * 2);
  const dv = new DataView(ab);
  wavHeader(dv, ch, len, sr);
  const chans = [];
  for (let c = 0; c < ch; c++) chans.push(buffer.getChannelData(c));
  return (async () => {
    let off = 44;
    for (let from = 0; from < len; from += CHUNK) {
      const to = Math.min(from + CHUNK, len);
      off = wavWriteFrames(dv, chans, from, to, off);
      if (onProgress) onProgress(to, len);
      await new Promise((r) => setTimeout(r, 0));   // 让出主线程，界面与定时器得以呼吸
    }
    return new Uint8Array(ab);
  })();
}

/** 从模型回复里抠出 JSON——它常带围栏、前后缀或多余解说。 */
function extractJSON(text) {
  if (typeof text !== "string") return null;
  let s = text.trim();
  const fence = s.match(/```(?:json)?\s*([\s\S]*?)```/i);
  if (fence) s = fence[1].trim();
  const first = s.indexOf("{"), last = s.lastIndexOf("}");
  if (first >= 0 && last > first) s = s.slice(first, last + 1);
  try { return JSON.parse(s); } catch (e) { /* 继续尝试修补 */ }
  try { return JSON.parse(s.replace(/,\s*([}\]])/g, "$1").replace(/[\u201c\u201d]/g, '"')); } catch (e) { return null; }
}

function fmtTime(sec) {
  if (!isFinite(sec) || sec < 0) sec = 0;
  const m = Math.floor(sec / 60), s = Math.floor(sec % 60);
  return m + ":" + (s < 10 ? "0" : "") + s;
}

/* 内置示例：真实模型产出的乐谱，离线也能听。纯数据，故放在引擎层。 */
const DEMO = {
  title: "夜色微光", mood: "静谧温柔忧郁", mode: "melody", bpm: 84, bars: 4,
  tracks: [
    { name: "Bass", wave: "triangle", gain: 0.22, notes: [["C2", 0, 1.5, 0.85], ["C2", 2.5, 1.5, 0.72], ["Ab2", 4, 1.5, 0.85], ["Ab2", 6.5, 1.5, 0.7], ["Eb2", 8, 1.5, 0.85], ["Eb2", 10.5, 1.5, 0.72], ["Bb2", 12, 1.5, 0.85], ["Bb2", 14.5, 1.5, 0.7]] },
    { name: "Arpeggio", wave: "sine", gain: 0.11, notes: [["C4", 0, 0.9, 0.6], ["Eb4", 1, 0.9, 0.55], ["G4", 2, 0.9, 0.6], ["Eb4", 3, 0.9, 0.5], ["Ab3", 4, 0.9, 0.6], ["C4", 5, 0.9, 0.55], ["Eb4", 6, 0.9, 0.6], ["C4", 7, 0.9, 0.5], ["Bb3", 8, 0.9, 0.6], ["Eb4", 9, 0.9, 0.55], ["G4", 10, 0.9, 0.6], ["Eb4", 11, 0.9, 0.5], ["Bb3", 12, 0.9, 0.6], ["D4", 13, 0.9, 0.55], ["F4", 14, 0.9, 0.6], ["F4", 15, 0.9, 0.5]] },
    { name: "Melody", wave: "square", gain: 0.09, notes: [["Eb5", 0, 1.5, 0.7], ["G5", 2, 1.5, 0.62], ["Ab5", 4, 2, 0.7], ["G5", 6.5, 1.5, 0.6], ["Bb5", 8, 2, 0.72], ["G5", 10.5, 1.5, 0.6], ["F5", 12, 2.5, 0.68], ["Eb5", 15, 1, 0.55]] },
  ],
  percussion: [["kick", 0, 0.9], ["kick", 4, 0.8], ["kick", 8, 0.9], ["kick", 12, 0.8], ["snare", 2, 0.5], ["snare", 6, 0.45], ["snare", 10, 0.5], ["snare", 14, 0.45], ["hat", 0.5, 0.3], ["hat", 1.5, 0.25], ["hat", 3.5, 0.25], ["hat", 5.5, 0.3], ["hat", 7.5, 0.25], ["hat", 9.5, 0.3], ["hat", 11.5, 0.25], ["hat", 13.5, 0.3]],
  fx: { reverb: 0.34 },
};

export {
  TIMBRES,
  TIMBRE_TIERS,
  TIMBRE_TIER_LABELS,
  DEFAULT_TIER,
  GROOVES,
  METERS,
  DEFAULT_METER,
  timbreNames,
  timbreLabel,
  timbreTierOf,
  normalizeScore,
  durationOf,
  beatsOf,
  meterOf,
  clamp,
  buildBus,
  scheduleRange,
  mkGain,
  renderOffline,
  encodeWavAsync,
  HEADROOM,
  midiToName,
  fmtTime,
};
